### ISSUE TITLE
I would like a batch delete option that will allow me to delete multiple rows in a single line

### ISSUE THREAD

**Issue by shavitohad** [remult/remult#103]
This is my local implementation, I wish it was in the api.

export async function deleteAll<entityType extends EntityBase>(repo: Repository<entityType>,
    where?: EntityFilter<entityType>) {
    for (const clientRow of await repo.find({ where })) {
        await repo.delete(clientRow);
    }
}

**Comment by noam-honig** [comment]
It makes senes to try and optimize the calls, so that deleting 100 rows, will not send 100 delete rest api call/sql statements.
On the other hand, if there is a `deleting` or `deleted` handler, we still need them to run before the delete.

**Comment by noam-honig** [comment]
#221
