### ISSUE TITLE
File uploading

### ISSUE THREAD

**Issue by kczepiec** [remult/remult#107]
Hello, any solution for file uploading and stream files via API?

**Comment by noam-honig** [comment]
There is no built in solution, but here is a sample angular project where I
use base64 to upload files and save them in an entity,

https://github.com/noam-honig/menb/blob/9304b3eba390eb0c422c13ad9aa6f9c92ad07f6d/src/app/bottle-info/bottle-info.component.ts#L146


And later resize them and download a small version of them:

https://github.com/noam-honig/menb/blob/9304b3eba390eb0c422c13ad9aa6f9c92ad07f6d/src/server/index.ts#L39

You can see the result at:

https://menb.herokuapp.com


Let me know if that helps
