### ISSUE TITLE
Is javascript supported?

### ISSUE THREAD

**Issue by mikicho** [remult/remult#115]
**Is your feature request related to a problem? Please describe.**
I prefer to use JSDoc (no build :P).

**Describe the solution you'd like**
Use remult with regular, simple js 

**Describe alternatives you've considered**
Nothing - I prefer not using TS

**Additional context**
https://gils-blog.tayar.org/posts/jsdoc-typings-all-the-benefits-none-of-the-drawbacks/

**Comment by noam-honig** [comment]
Short answer, yes.

Here's an example todo app with react, vite & express that uses js and not typescript:
https://github.com/noam-honig/react-vite-express-js

The key difference in using javascript, is to replace the `decorator` syntax used in `typescript` - please take a look at the readme where it's explained in more depth.

Also - we are working on making that even easier :)

But we've tested it and it works great.

**Comment by noam-honig** [comment]
Please note that the remult version used in the sample is experimental and will be released as latest in the coming weeks (days :)
