### ISSUE TITLE
Version 0.16 fails to load in Deno

### ISSUE THREAD

**Issue by yoni-rapoport** [remult/remult#131]
**To Reproduce**
1. Clone https://github.com/yoni-rapoport/fresh-remult-todo
2. Replace remult version from 0.15 to 0.16
3. `deno task start`
4. App doesn't load

**Expected behavior**
App should load successfully - as with v0.15.

**Comment by noam-honig** [comment]
Fixed it, @yoni-rapoport please test and release

**Comment by yoni-rapoport** [comment]
Fixed and released v0.16.3

**Comment by meacu1pa** [comment]
Thank you both, that was insanely fast! Can confirm that it also works on my end now.
