### ISSUE TITLE
error when make tutorial remult for Nextjs: ReferenceError: hideCompleted is not defined

### ISSUE THREAD

**Issue by quangtynu** [remult/remult#144]
Unhandled Runtime Error
ReferenceError: hideCompleted is not defined

Source
pages/index.tsx (10:24) @ fetchTasks

   8 |   limit: 20,
   9 |   orderBy: { completed: "asc" },
> 10 |   where: { completed: hideCompleted ? false : undefined }
     |                      ^
  11 | });
  12 | }
  13 | 
Call Stack
eval
pages/index.tsx (19:4)
Show collapsed frames

**Comment by noam-honig** [comment]
Hu @quangtynu ,

Can you please verify that you've added the hideCompleted argument to the `fetchTasks` method at:
https://remult.dev/tutorials/react-next/sorting-filtering.html#toggle-display-of-completed-tasks

![image](https://user-images.githubusercontent.com/16635859/204245360-89319fcc-0bde-4d96-a4a2-ca5604c77b67.png)


Let me know

**Comment by quangtynu** [comment]
Oh, Thank you. I forgot to add argument. Now it ok.
