### ISSUE TITLE
In angular how can I handle error message in one way

### ISSUE THREAD

**Issue by pbpoon** [remult/remult#170]
I already set  remult.apiClient.httpClient = http (angular HttpClient) in angular AppModule constructor
and I set an angular interceptor also
but in remult repo operation throw error, I can't get any error intercept message
just can do try catch get the error
I want easily to handle the error in one way
another idea?
thanks

**Comment by noam-honig** [comment]
Hi,

You can setup a general angular error handler that'll catch all ancaught exceptions and work based on it.

You inject it as a provider:
  
  import { NgModule, ErrorHandler } from '@angular/core';
  ...
  providers: [{ provide: ErrorHandler, useClass: ShowDialogOnErrorErrorHandler }],
  
 
 
Let em know if that helps

**Comment by pbpoon** [comment]
> Hi,
> 
> You can setup a general angular error handler that'll catch all ancaught exceptions and work based on it.
> 
> You inject it as a provider:
> 
> import { NgModule, ErrorHandler } from '@angular/core'; ... providers: [{ provide: ErrorHandler, useClass: ShowDialogOnErrorErrorHandler }],
> 
> Let em know if that helps

great! I get it
thank you
