### ISSUE TITLE
I want to know need migration?

### ISSUE THREAD

**Issue by pbpoon** [remult/remult#171]
I check the document, can't find any about database migration subject
in production env ,migration is important to control database migrate

**Comment by noam-honig** [comment]
Check out discussion #162, I just updated it with the latest state.

We have an option called `ensureSchema` that defautls to true, and that will make sure all entities and columns exist in the database.

I also outline in #162 a sample implementation of a version engine that I use in my other projects.

Let me know if that's ok for you

**Comment by pbpoon** [comment]
I read this discussion, I think your solution is not the better now, maybe you can reference Python Django or Prisma migration command line to use is easily 
look forward Remult will better, I like it.
thank you
