### ISSUE TITLE
Query with Where breaks when converting to lowercase

### ISSUE THREAD

**Issue by amrit92** [remult/remult#172]
**Describe the bug**
Tried running the crm-demo and noticed that this line here breaks https://github.com/remult/crm-demo/blob/master/src/Contacts/ContactsPage.tsx#L57.

I think remult is trying to downcase column names by default but the columns in postgres that are created look like camelCase: firstName, lastName. 

Query:
```
          $or: [
            { firstName: { $contains: filter.search } },
            { lastName: { $contains: filter.search } }
          ],
```
Below is the error:
```

[API]   message: `select "id", "orgId", "firstName", "lastName", "gender", "title", "company", "phoneNumber1", "phoneNumber2", "background", "acquisition", "email", "avatar", "hasNewsletter", "accountManager", "status", "lastSeen", "createdAt" from "contacts" where ("orgId" = $1 and ((lower (firstName) like lower ('%%')) or (lower (lastName) like lower ('%%')))) order by "lastName" asc limit $2 - column "firstname" does not exist`,
[API]   stack: [
[API]     `error: select "id", "orgId", "firstName", "lastName", "gender", "title", "company", "phoneNumber1", "phoneNumber2", "background", "acquisition", "email", "avatar", "hasNewsletter", "accountManager", "status", "lastSeen", "createdAt" from "contacts" where ("orgId" = $1 and ((lower (firstName) like lower ('%%')) or (lower (lastName) like lower ('%%')))) order by "lastName" asc limit $2 - column "firstname" does not exist`,


```

If I don't use contains it works fine:

```
         $or: [
            { firstName:  "Lou"  },
          ],

```
**To Reproduce**
1. Run crm-demo

**Expected behavior**
No error logs

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noam-honig** [comment]
Hi @amrit92,

I wonder why I don't see this on the deployed version of the crm-demo that runs on railway (or previously on heroku)

Any how - I was able to reproduce and solve this issue - please test version [v0.18.1](https://github.com/remult/remult/releases/tag/v0.18.1) and let me know if this works for you.

Best
Noam

**Comment by amrit92** [comment]
Amazing! Thanks for the superfast fix.  I've tested and it looks good.
