### ISSUE TITLE
AllowedForInstance for allowApiRead

### ISSUE THREAD

**Issue by groszdaniel** [remult/remult#175]
**Is your feature request related to a problem? Please describe.**
It's common that only some users should have access to particular rows in a table. For instance, each user has settings or other data, so each row has a `user` field specifying the user it belongs to, and only the rows that belong to the currently authenticated user should be allowed to be read.

**Describe the solution you'd like**
Please make the allowApiRead property of an Entity be an AllowedForInstance instead of a plain Allowed, just like allowApiUpdate etc.

**Describe alternatives you've considered**
The only alternative I see is to solely use BackendMethods for reading and set allowApiRead to false in these cases. However, this loses much of the convenience provided by Remult repos. If there is a solution I don't see, please document it in the docs.

**Comment by noam-honig** [comment]
@groszdaniel 

Check out [apiPreFilter](https://remult.dev/docs/ref_entity.html#apiPreFilter), we created that to achieve the same goal.
You can define a filter there, based on the user, that we'll be applied for all API queries done by that user.

For example - only the admin can see archived rows:

```ts
@Entity("people",{
allowApiRead:true,
   apiPreFilter:()=>!remult.isAllowed("admin")?{archive:false}:{}
})
export class Person{
...
}
```

Check it out and let us know if that helps achieve what you're looking for.

**Comment by noam-honig** [comment]
@groszdaniel I agree, I've made an adjustment and applied it.

Check it out:
https://remult.dev/docs/ref_entity.html#apiprefilter
