### ISSUE TITLE
Postgres AutoIncrement field doesn't update or save when changing the field

### ISSUE THREAD

**Issue by MartyHas** [remult/remult#176]
**Describe the bug**
I defined an autoincrement field in the entity. This filed is not changable by either update or save method. However, raw postgres does let you run an update statement.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noam-honig** [comment]
@MartyHas 

Try setting it's `dbReadOnly` property to false

  @Fields.autoIncrement({
    dbReadOnly: false,
  })
  id = 0;
  
The defaults for `autoIncrement` are defined at:
https://github.com/remult/remult/blob/5457594ab32104b48da9a7d6414290439aa82a38/projects/core/src/remult3/RepositoryImplementation.ts#L1673-L1679

Let me know that it worked?

**Comment by amrit92** [comment]
@noam-honig  I tried this, for both update/save it now always sets the field to the default value (0), but not the value that I'm specifying in the update/save. 

```
  @Fields.autoIncrement({
    dbReadOnly: false,
  })
  orgId = 0
```

**Comment by MartyHas** [comment]
@noam-honig  I tried this, for both update/save it now always sets the field to the default value (0), but not the value that I'm specifying in the update/save. 

```
  @Fields.autoIncrement({
    dbReadOnly: false,
  })
  orgId = 0
```

**Comment by noam-honig** [comment]
I see, if you are updating from the frontend, also set:
allowApiUpdate:true.
And it’ll allow update from the front end.

Can you try?

**Comment by MartyHas** [comment]
Thanks, that works!
