### ISSUE TITLE
Deletion fails with Fastify

### ISSUE THREAD

**Issue by toBeOfUse** [remult/remult#177]
**Describe the bug**
When I try to delete a database item, the frontend Remult code sends a DELETE request to the backend with an empty body. However, a Fastify backend server will then complain that an empty body is invalid because the Content-Type header is set to application/json, and an empty string is not technically valid JSON. A similar issue for another framework is documented [here](https://github.com/marmelab/react-admin/issues/5452).

There seems to be some argument that Fastify is being too strict, but since Fastify support is mostly there in Remult already, fixing this would be nice.

**To Reproduce**
Set up Remult with Fastify. Create an entity and insert an instance of it. In frontend code, attempt to delete the instance.

**Expected behavior**
Ideally the item would be deleted. This would happen if the Content-Type header on the request was not set or was set to text/plain or something broad like that.

**Screenshots**

![image](https://user-images.githubusercontent.com/49729978/230749205-9a573c11-9fe5-4460-af89-1c16d1e90c53.png)

![image](https://user-images.githubusercontent.com/49729978/230749208-b34c38db-f9ba-4341-8e57-cae0e1afc677.png)

**Non-Remult Fix**

In the backend code, this problem can be fixed by adding a less strict parser to Fastify:

```ts
fastify.addContentTypeParser(
  "application/json",
  { parseAs: "string" },
  function (req, body: string, done) {
    try {
      if (!body) {
        // don't try to parse an empty body
        done(null, null);
      } else {
        done(null, JSON.parse(body));
      }
    } catch (err: any) {
      err.statusCode = 400;
      done(err, undefined);
    }
  }
);
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 111.0.1 (64-bit)

**Comment by toBeOfUse** [comment]
It seems like this could be changed to only include this header if options.body has content: https://github.com/remult/remult/blob/355f183c3da7c7a4bf0c7040e25101c9f4d2a963/projects/core/src/data-providers/rest-data-provider.ts#L208-L215

**Comment by noam-honig** [comment]
Fixed it on https://github.com/remult/remult/releases/tag/v0.19.2

Can you check it out and let me know?

**Comment by toBeOfUse** [comment]
After upgrading to 0.19.2, DELETE requests work in my Fastify project without the modified JSON parser thing I was using before, thanks. I'll close this since I believe the issue is completely fixed

![image](https://user-images.githubusercontent.com/49729978/230796278-2c58db08-77e2-4518-9d81-a49729824748.png)
