### ISSUE TITLE
Is there a way to have bidirectional relationships between entities?

### ISSUE THREAD

**Issue by grrenier** [remult/remult#180]
For example: 

`class House {
   @Fields.object<House>((options, remult) => {
        options.serverExpression = async (house) =>
            remult.repo(HouseOwner).find({where: { house: { $id: house.id }})
    })
   owners?: HouseOwner[] = [];
}

class Person {
   name: string;
}

class HouseOwner {
  @Field(() => Person)
  person?: Person;

  @Field(() => House)
  house?: House;
}
`

When I have a bidirectional relationship like House and HouseOwner I'm getting this error "_FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory_"

**Comment by noam-honig** [comment]
It seems that you have a circular loading scenario that is causing the issue.

When you load a house, it tries to load it's HouseOwner, but the HouseOwner has a House field, that tries to load the HouseOwner again etc...

You can prevent that in several ways:
1. Mark House as [lazy](https://remult.dev/docs/lazy-loading-of-related-entities.html) in the HouseOwner entity.
2. In the call to the `find` method, add `load:()=>[]` which will instruct the code not to load the referenced entities.
3. You can also only store the House id on the HouseOwner entity and you wouldn't run into this in the first place.

One more fix, in the code where you load the HouseOwner, you seem to struggle with the id, you can simply say:
```ts
remult.repo(HouseOwner).find({where: { house: house }})
})
```
and it should work.

On a personal note, I don't like `serverExpression`s that are heavy - as they run always, not only when I want them.
I would use a separate fetch, to load the HouseOnwers - but that's just me

**Comment by grrenier** [comment]
Perfect, it works when I mark it as lazy. Is there a way to mark the HouseOwner list as lazy? or is it better to implement a backend method like you said? Also the serverExpression works always even if I mark that as lazy?

**Comment by noam-honig** [comment]
@grrenier, currently lazy doesn't affect server expressions.
You don't necessarily need a backend method for this, you can simply read the HouseOwner array from the front end with another query.
