### ISSUE TITLE
Feature request: Enclose column names in generated postgres SQL with double quotes

### ISSUE THREAD

**Issue by ChrisRimmer** [remult/remult#182]
I just ran into an issue when trying to create an entity that related to my User entity - I named the relating field (and thus, the column in the database which would contain the user ID) on my new entity "user" which caused Postgres to explode when trying to generate the table or insert new rows, as "user" is a reserved word in Postgres.

Having tested manually, it seems that wrapping field names in double-quotes on table creation and inserts seems to fix this behaviour, I would guess because the double quote forces Postgres' query parser to read a column name rather than a language keyword.

Using reserved words as column names seems does seem to be frowned upon a little bit, but Postgres' own documentation suggests that some reserved words can be used as identifiers (unlike in SQL where that seems strictly forbidden) so I think this seems to be acceptable in the spec?

**Comment by noam-honig** [comment]
Hi  @ChrisRimmer,

You can use the `dbName` field option to add quotes to the column name in the db - or even use a different column name than the name of the field in Typescript.

```ts
@Fields.string({
  dbName:'"user"'
})
user=''
```

Alternatively - the knex provider for Postgres does add the quotes - see [knex postgres](https://remult.dev/docs/databases.html#postgres)

But If I were you, I would use the `dbName` option (which I use for these cases)

Try it out and let me know what you think.

**Comment by ChrisRimmer** [comment]
Nice. I had already hacked around this problem myself by creating the table manually but next time this comes up I'll try that. Cheers!
