### ISSUE TITLE
Upgrade dependencies versions in Next.js tutorial starter repo 

### ISSUE THREAD

**Issue by maral** [remult/remult#185]
In the Next.js tutorial, I got stuck [here](https://remult.dev/tutorials/react-next/auth.html#role-based-authorization-on-the-frontend):
![image](https://github.com/remult/remult/assets/1295186/805e82c3-e7c4-4c56-8d66-8b9473974ff1)

That's because while the tutorial expects to use remult v0.19.0 or newer (the resulting example in repo uses v0.20.0), the [starter repo](https://github.com/remult/nextjs-starter) uses remult v0.18.0 which has different property type (apiDeleteAllowed is boolean, not function).

The simplest fix would be to use this [package.json](https://github.com/remult/remult/blob/master/examples/nextjs-todo/package.json) from the final example in this repo.

Also, some kind of changelog would be nice (so I don't have to search for the changes in the source code directly), but I understand it is still alpha/beta stage rn. Remult is great!

**Comment by noam-honig** [comment]
Sorry about that - I've fixed it:)

**Comment by noam-honig** [comment]
As for the changelog - is the release notes enough?

If not - we try to maintain a release note file in the repo, is that what you hand in mind?
https://github.com/remult/remult/blob/master/projects/core/release-notes.md

**Comment by maral** [comment]
Oh shoot, that's perfect, I just didn't find it. Maybe you could include a link to it in the README file, so it's easier to find?

**Comment by noam-honig** [comment]
I've renamed it to CHANGELOG.md, you can find it at:
https://github.com/remult/remult/blob/master/CHANGELOG.md
