### ISSUE TITLE
Live Query doesn't support LoadOptions.load

### ISSUE THREAD

**Issue by SpeedoPasanen** [remult/remult#196]
Overriding the default loading of related entities doesn't work in Live Queries. This always tries to load all related entities, and throws 403 if user doesn't have read access for some related entity:

```ts
repo.liveQuery({ load: (fieldsMeta) => [] })
```

While this works as expected:

```ts
repo.find({ load: (fieldsMeta) => [] })
```

**Comment by noam-honig** [comment]
Hi @SpeedoPasanen, I believe I fixed it in version https://github.com/remult/remult/releases/tag/v0.20.4

Can you check it out?
