### ISSUE TITLE
Is there a way to run repo insert or update queries in a transaction?

### ISSUE THREAD

**Issue by grrenier** [remult/remult#200]
I there a way to run multiple insert/update queries inside a MongoDB transaction, for example when we do a deposit into an account we need to insert the deposit amount in the `AccountTransaction` and then update the `Account` balance but that should be a transaction to be able to do a rollback when there is any error.

**Comment by noam-honig** [comment]
Currently, `BackendMethod` runs in a transaction.

I agree that also, api insert and api update should run in a transaction, and I'll implement that soon.

**Comment by noam-honig** [comment]
If you run these multiple operations in a `BackendMethod` they will run in a transaction.

Test it and let me know

**Comment by grrenier** [comment]
I did something like this and the first employee was saved to the DB. Should I do something different?
```
export class EmployeeController {
  @BackendMethod({ allowed: Allow.authenticated })
  static async testDbTransaction(employee1: Employee, employee2: Employee): Promise<Employee> {
    const e1 = await remult.repo(Employee).insert(employee1);
    if (true) {
      throw Error('Abort DB transaction');
    }
    const e2 = await remult.repo(Employee).insert(employee2);
    return e1;
}
```

**Comment by noam-honig** [comment]
I've reproduced the issue and am working on it now

**Comment by noam-honig** [comment]
Hi @grrenier, I've fixed the issue in this release:
https://github.com/remult/remult/releases/tag/v0.20.5

Can you check it out and let me know?

**Comment by grrenier** [comment]
Hi @noam-honig, I tested the version 0.20.5 and it works as expected. You are doing an awesome work in this framework.
