### ISSUE TITLE
Allow updating individual fields without passing the entire object to `Repository.update`

### ISSUE THREAD

**Issue by WeiN76LQh** [remult/remult#202]
**Is your feature request related to a problem? Please describe.**
Currently, updating an object is done using the following code:

```typescript
taskRepo.update(task.id,{...task,completed:true})
```

Spreading the task object here seems unnecessary as the desire is to only change `completed` to `true`. This example is taken from the documentation and I don't see any other example or mention of being able to just update a single field (or multiple) without spreading the entire object before the updated values.

I imagine the purpose is because certain fields could be undefineable and therefore there's no way to differentiate between a field being updated to be `undefined` and that field not being updated, as in both cases its value would be `undefined`.

The problem is that there could be a race where client A updates field A of an object but before client B receives the update to field A, it updates field B with its now outdated version of the object. Client B will therefore cause field A to be rolled back to its value before client A updated it because it spreads the old version of the object as part of the update request. Whilst racey issues are always a problem when there are multiple clients working on the same data, in this instance it feels like it could be somewhat mitigated.

**Describe the solution you'd like**
The ability to set the value of individual fields without having to spread the entire object. For example:

```typescript
taskRepo.update(task.id,{completed:true})
```

If I am correct in presuming that the reason for this is due to fields that can be set to `undefined` then maybe have an additional parameter to `update` that can be used to specify a field should be set to `undefined`. Or could setting the value to `null` work? For example:

```typescript
taskRepo.update(task.id,{completed:true},{fieldThatCanBeUndefined: true})
```

Or:

```typescript
taskRepo.update(task.id,{completed:true, fieldThatCanBeUndefined: null})
```

**Describe alternatives you've considered**
Presumably this could be solved using a `BackendMethod` and maybe some direct access to the SQL database but it doesn't feel like it should need to be like that and would probably require a decent amount of boilerplate code.

**Additional context**

**Comment by noam-honig** [comment]
@WeiN76LQh not sure why I didn't reply before - but `update` works the way you expect it today, it doesn't require the spread.

**Comment by WeiN76LQh** [comment]
@noam-honig apologies, I posted this issue over a year ago but at the time my account was shadow banned. I didn't get it unbanned until recently and I forgot I had posted this issue. I guess once it got unbanned the issue became visible to other poeple.
