### ISSUE TITLE
Backend subscriptions (for event driven apps) or API route hooks

### ISSUE THREAD

**Issue by alexkreidler** [remult/remult#212]
**Is your feature request related to a problem? Please describe.**
I'd like to add some additional backend logic that happens whenever a `POST /api/myEntity` or another operation on that entity is requested. It should be able to receive the body data and do some processing, likely asynchronously, while Remult persists the entity to the database.

**Describe the solution you'd like**
One option is like the [Live Queries](https://remult.dev/tutorials/react-next/live-queries.html)/subscriptions feature, where I register a `myEntityRepo.subscribe(({items, applyChanges, changes}) => { // my logic })` handler. Likely using the `changes` field I can handle different events corresponding to various HTTP verbs.

Another option would be "hooks" for the regular CRUD API routes, like:
```ts
  @BackendMethod({ hook: true })
  static async insert(entity: Entity) {
    const entityRepo = remult.repo(Entity)

    await Promise.all([
      entityRepo.save(entity),
      async () => {
        kafka.send({entity})
      }
    ])

    //  or just
    await Promise.all([
      entityRepo.insert(entity),
      async () => {
        kafka.send({entity})
      }
    ])
  }

  // or

  static async beforeInsert(entity: Entity) {
    entity.name = entity.name.toUpperCase();
    return entity
  }
```

**Describe alternatives you've considered**
I looked at `BackendMethod`s, but AFAICT I'd need to add duplicate API routes for every action I wanted to override, breaking the uniform HTTP and remult frontend library interfaces. I'd like to be able to override those routes to perform slightly different logic but still have the easy default action as an ideally one-line function call.

**Comment by yoni-rapoport** [comment]
Try using the Entity lifecycle hooks `saving` / `saved` of the options object sent to `@Entity`.

See example here:
https://github.com/remult/crm-demo/blob/master/src/Contacts/ContactNote.entity.ts#L11
