### ISSUE TITLE
DisableTransactions in MongoDB, debugging Cosmos DB for MongoDB

### ISSUE THREAD

**Issue by elier** [remult/remult#215]
**Describe the bug**

Not sure if the DisableTransactions option is being taken into consideration when passed, in the code it looks like hardcode to false, and never used:
https://github.com/remult/remult/blob/fc2f5c6d67fb43632fdc8ae1b7242fff32a7fc55/projects/core/remult-mongo.ts#L37

My code:
```
MongoDataProvider(client.db((process.env as any).MONGODB_DATABASE_NAME), client, { disableTransactions: true });
```

I wanted to disable transactions because I'm getting the following error:
```
Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 1101; ActivityId: 4a5f881b-e63d-4756-981e-23b60d6428e4; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 1101; ActivityId: 4a5f881b-e63d-4756-981e-23b60d6428e4; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 1101; ActivityId: 4a5f881b-e63d-4756-981e-23b60d6428e4; Reason: (Message: {"Errors":["Transaction is not active"]}
```

**Comment by noam-honig** [comment]
Thanks.
I've fixed it in version 0.22.1 (https://github.com/remult/remult/releases/tag/v0.22.1)

Can you check it and let me know that it's ok?

**Comment by elier** [comment]
Yes! { disableTransactions: true } works now!

I still got the following error from Cosmos DB if I set disableTransaction to false.
```
Reason: (Message: {"Errors":["Transaction is not active"]}
```

According to Cosmos DB for MongoDB documentation:   
Multi-document transactions are supported within an unsharded collection in API version 4.0. Multi-document transactions are not supported across collections or in sharded collections in 4.0. The timeout for transactions is a fixed 5 seconds.
https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/use-multi-document-transactions

I'm using Cosmos DB 4.2 API, and unsharded collection. However, I simple reading operation from a static backendMethod cause Cosmos DB to trigger the error. 

My code:
```
const user = await remult.repo(User).findFirst({ email: email });
``` 

I wonder why remult "transaction" is considered multi-document while I'm only doing a simple read to one collection?
Or it is Cosmos DB that is not accepting transactions at all even when the documentation says so.

Any thoughts?
Thanks

**Comment by noam-honig** [comment]
Are you still getting the error?

**Comment by noam-honig** [comment]
Perfect - I thought you had another error - I'm happy that you don't.

Cheers
