### ISSUE TITLE
Storing dates differently during create vs update in MongoDB

### ISSUE THREAD

**Issue by elier** [remult/remult#216]
**Describe the bug**
When an entity with a date attribute is created, the date is stored as an object: { "$date" : 1688702400000 }.
However, when the entity is updated, the date is stored as a string: "2023-07-29T13:46:26.037Z".
The date attributes of the object (entity) being passed to remult.repo().insert() and remult.repo().update() are date instances, according to what I see in the console.

Therefore, it looks like the insert and the update are handling the date differently, not sure if it is remult or mongodb.

**Screenshots**
![image](https://github.com/remult/remult/assets/977320/0c17707d-e0e5-45b8-a31e-cebe785f02dd)
![image](https://github.com/remult/remult/assets/977320/1552521a-0899-4ead-a90a-3eeebbca6c7b)

**Versions**
```
"mongodb": "^5.3.0"
"remult": "^0.22.1"
```

**Comment by noam-honig** [comment]
Thanks for that, fixed it for version 0.22.2, can you please check?

**Comment by elier** [comment]
Fixed, thanks!
