### ISSUE TITLE
Create Entities Based on an Existing Database

### ISSUE THREAD

**Issue by Yedidyar** [remult/remult#218]
I am trying to achieve the same thing as the Prisma cli pull operation, which enables creating schema based on an existing database. 

For example see the [migration guide from sequelize to prisma](https://www.prisma.io/docs/guides/migrate-to-prisma/migrate-from-sequelize).

Does this kind of functionality exist?

**Comment by noam-honig** [comment]
I have some code samples for that - which db are you using?

**Comment by Yedidyar** [comment]
Postgres can you add link

**Comment by noam-honig** [comment]
Checkout this code, it creates an entity based on tables in the db

https://github.com/remult/remult/blob/master/projects/core/postgres/getEntityTypescriptPostgres.example


I didn’t create a cli yet, but you can call it from initApi. Check it out
and let me know what you think

**Comment by Yedidyar** [comment]
Looking good 😄
Maybe i will create a CLI for that next week.

**Comment by noam-honig** [comment]
Sounds great

**Comment by jycouet** [comment]
FYI, I used your example a few weeks back and improved a few things _(Of course, I don't remember exactly what...)_.
Maybe it gives some inspiration for others: 
https://gist.github.com/jycouet/581e6c4060217d4008099eacd890bca0
_This was post `ValueListFieldType` knowledge, I would like enums to turn into ValueListFieldType. (TODO)_

In coming weeks, I'll have to go back at it to switch a "big" project.

**Comment by noam-honig** [comment]
> Looking good 😄 Maybe i will create a CLI for that next week.

Would love to see a cli - looking forward to it

**Comment by Yedidyar** [comment]
I started working on the [cli](https://github.com/Yedidyar/remult-cli)

i am not sure if ink is the right solution

**Comment by jycouet** [comment]
Just 
```bash
npx remult-cli
``` 
and enjoy 🥳
https://github.com/Yedidyar/remult-cli
