### ISSUE TITLE
Issue in Angular Tutorial: cannot find async_hooks

### ISSUE THREAD

**Issue by manfredsteyer** [remult/remult#220]
**Describe the bug**
When using Remult in an Angular frontend, like described in the tutorial, just importing from 'remult' brings up the following error:

```
Error: node_modules/remult/src/context.d.ts:11:45 - error TS2307: Cannot find module 'async_hooks' or its corresponding type declarations.

11     constructor(remultObjectStorage: import('async_hooks').AsyncLocalStorage<Remult>);
                                               ~~~~~~~~~~~~~
```

**To Reproduce**
1. Create an angular application
2. add `import { remult } from 'remult';` to a component
3. start the Angular application
4. You will get the error mentioned above

**Additional context**
I've tried this out with Angular 16.1 and I followed the Angular tutorial on the remult site.

**Comment by noam-honig** [comment]
I see it now, it seems that angular changed something in it's latest version to load things that it shouldn't. I'm working on it right now, in the meantime don't let it stop you from trying out the tutorial, simply checkout the starter project :
```ts
git clone https://github.com/remult/angular-express-starter.git remult-angular-todo
cd remult-angular-todo
npm install
```

It uses angular 15

**Comment by noam-honig** [comment]
I've fixed it on version [0.22.5](https://github.com/remult/remult/releases/tag/v0.22.5)

Can you please test and confirm that it works?

**Comment by manfredsteyer** [comment]
Thanks for the quick help. The new version works like a charm.

**Comment by noam-honig** [comment]
Happy to hear that
