### ISSUE TITLE
Soft Delete field type

### ISSUE THREAD

**Issue by blalan05** [remult/remult#223]
**Is your feature request related to a problem? Please describe.**
A common DB ORM feature is the ability to have a deletedAt date column that gets updated with deleting, so the row isn't actually deleted, but there is a simply way to not return deleted with a flag.

**Describe the solution you'd like**
Add deletedAt field type (similar to createdAt and updatedAt), that is controlled by API if softDelete (or paranoid) flag on entity. If softDelete (or paranoid) flag on Entity, then { where: { deletedAt: null } } filter should be automatically added in find

**Describe alternatives you've considered**
All this could be done in userland with a lot of boilerplate.

**Additional context**
[Elequent ORM example](https://laravel.com/docs/5.0/eloquent#soft-deleting)
[Sequelize example](https://sequelize.org/docs/v6/core-concepts/paranoid/#defining-a-model-as-paranoid)

**Comment by noam-honig** [comment]
You can easily use https://remult.dev/docs/ref_entity#apipreprocessfilter to achieve that - let me know if you want me to prepare an example
