### ISSUE TITLE
Many-to-Many Relationship

### ISSUE THREAD

**Issue by blalan05** [remult/remult#224]
**Is your feature request related to a problem? Please describe.**
I'd like to create complex relationship with through tables.
```
User
id
name
```

```
UserToType
userId
userTypeId
```

```
UserType
id
name
```

**Describe the solution you'd like**
Add the ability to define Many-to-Many relationships

**Describe alternatives you've considered**
I think its possible to define through table manually, then use the relationship definition like One-to-Many.

**Additional context**

**Comment by noam-honig** [comment]
Hi @balan05 & @Vincent1016  - sorry for not replying earlier

In the current version of remult, you can do that with a 'through' table
```ts
@Entity('users')
class User {
  @Fields.cuid()
  id = ''
  @Fields.string()
  name = ''
}
@Entity('UserTypes')
class UserType {
  @Fields.cuid()
  id = ''
  @Fields.string()
  name = ''
}
@Entity<UserToType>('UsersToTypes', {
  id: (e) => [e.userId, e.typeId],
})
class UserToType {
  @Fields.string()
  userId = ''
  @Fields.string()
  typeId = ''
}
```

You can employ advanced filtering techniques as detailed in:
https://remult.dev/docs/techniques-regarding-one-to-many-relations.html

You can also add many to one relations to the mix - but in that case, at the current version, I recommend adding a separate id column for good measure

```ts
@Entity<UserToType>('UsersToTypes')
class UserToType {
  @Fields.cuid()
  id = ''
  @Field(() => User, { lazy: true //to only load when requested 
    })
  userId!: User
  @Field(() => UserType)
  typeId!: UserType
}
```

You can use `lazy` to control if the other row is loaded by default or not - see:
https://remult.dev/docs/lazy-loading-of-related-entities.html#lazy-loading-of-related-entities


We are currently planning some improvements in the relations area, stay tuned

**Comment by mihaa1** [comment]
> Hi @balan05 & @Vincent1016 - sorry for not replying earlier
> 
> In the current version of remult, you can do that with a 'through' table
> 
> ```ts
> @Entity('users')
> class User {
>   @Fields.cuid()
>   id = ''
>   @Fields.string()
>   name = ''
> }
> @Entity('UserTypes')
> class UserType {
>   @Fields.cuid()
>   id = ''
>   @Fields.string()
>   name = ''
> }
> @Entity<UserToType>('UsersToTypes', {
>   id: (e) => [e.userId, e.typeId],
> })
> class UserToType {
>   @Fields.string()
>   userId = ''
>   @Fields.string()
>   typeId = ''
> }
> ```
> 
> You can employ advanced filtering techniques as detailed in: https://remult.dev/docs/techniques-regarding-one-to-many-relations.html
> 
> You can also add many to one relations to the mix - but in that case, at the current version, I recommend adding a separate id column for good measure
> 
> ```ts
> @Entity<UserToType>('UsersToTypes')
> class UserToType {
>   @Fields.cuid()
>   id = ''
>   @Field(() => User, { lazy: true //to only load when requested 
>     })
>   userId!: User
>   @Field(() => UserType)
>   typeId!: UserType
> }
> ```
> 
> You can use `lazy` to control if the other row is loaded by default or not - see: https://remult.dev/docs/lazy-loading-of-related-entities.html#lazy-loading-of-related-entities
> 
> We are currently planning some improvements in the relations area, stay tuned

Hey,
Related - when using relations as in docs - should an underlined foreign key be created?
Im using postgres - either I'm missing something or it is not created

**Comment by noam-honig** [comment]
Hi @mihaa1 

No, at this time we do not generate a foreign key in the db by default - we only generate the structure to store the data, and leave it to the developer to create the meta data objects such as indexes, foreign keys etc...

You can easily do that as part of the version update process discussed in:
https://github.com/remult/remult/discussions/162

**Comment by mihaa1** [comment]
> Hi @mihaa1
> 
> No, at this time we do not generate a foreign key in the db by default - we only generate the structure to store the data, and leave it to the developer to create the meta data objects such as indexes, foreign keys etc...
> 
> You can easily do that as part of the version update process discussed in: #162

Thanks.
Rules of relations are enforced by code then inside remult?
e.g. creating relation with non existent id
