### ISSUE TITLE
Add Documentation for remult-cli in the Official Remult Docs

### ISSUE THREAD

**Issue by Yedidyar** [remult/remult#235]
[`remult-cli`](https://github.com/Yedidyar/remult-cli) is a powerful command-line utility designed to streamline the generation of Remult entities from a PostgreSQL database. Currently, it appears that there is no mention of `remult-cli` in the official documentation. I propose that we add a section dedicated to this CLI tool to help users understand its functionality and how to integrate it into their Remult projects.

Suggested Locations:
As a subsection under the "Getting Started" guide
As a standalone guide within the "Integrations" section

@jycouet @noam-honig, I'd love to hear your thoughts on where this information would be most effectively placed. Thank you!

**Comment by yoni-rapoport** [comment]
Hi @Yedidyar pls check out #237. 

Do you have any suggestions before I publish?

**Comment by Yedidyar** [comment]
@yoni-rapoport looks good
