### ISSUE TITLE
SvelteKit Example

### ISSUE THREAD

**Issue by djamez** [remult/remult#238]
I noticed that there are tutorials for the supported frameworks, except for Sveltekit

I would like to contribute a Sveltekit tutorial in the same vein as the existing frameworks.

**Comment by jycouet** [comment]
You probably know, but there is an example here:
```sh
npx degit remult/remult/examples/sveltekit-todo remult-sveltekit-todo
cd remult-sveltekit-todo
```

For the  tutorial, you could probably start from this PR: https://github.com/remult/remult/pull/226

**Comment by djamez** [comment]
@jycouet : Did you get a chance to review the PR #246?

**Comment by jycouet** [comment]
Yes, you didn't see my first comments?

**Comment by jycouet** [comment]
I guess we can close this now
