### ISSUE TITLE
KnexDataProvider - Expected date but got Invalid Date

### ISSUE THREAD

**Issue by elier** [remult/remult#248]
**Describe the bug**
A date field becomes  "Invalid Date" object and the insert fails.

**To Reproduce**
Put a date field in an entity:
```
  @Fields.date()
  date: Date;
```
```
await remult.repo(Person).insert({"date": new Date()});
```

**Desktop (please complete the following information):**
Node: 18.17.0
OS: darwin arm64
remult: ^0.22.7

**Additional context**
```
  dataProvider: createKnexDataProvider({
    // Knex client configuration for MySQL
    client: "mysql2",
    ...
```

You may want to validate dates like this in ValueConverters.js, because "Invalid Date" is instanceof Date:
```
     if (val instanceof Date && !isNaN(val.valueOf())) {
```

**Comment by elier** [comment]
If I change the code like this, it all works fine:
```
@Fields.string()
date: string;
```
```
await remult.repo(Person).insert({"date": "2023-09-22"});
```
Something

**Comment by noam-honig** [comment]
Hi @elier, I tried to reproduce the issue, and couldn't.

Here's the code I used to try to reproduce the issue, can you checkitout?
```ts
import { Entity, Fields, remult } from "remult"
import { createKnexDataProvider } from "remult/remult-knex"

@Entity("person")
class Person {
  @Fields.integer()
  id = 0
  @Fields.date()
  theDate: Date
}

createKnexDataProvider({
  // Knex client configuration for MySQL
  client: "mysql",
  connection: {
    user: "root",
    password: "MASTERKEY",
    host: "127.0.0.1",
    database: "test",
    port: 36061,
  },
}).then(async (db) => {
  remult.dataProvider = db
  const repo = remult.repo(Person)
  await db.knex.schema.dropTableIfExists(await repo.metadata.getDbName())
  await db.ensureSchema([repo.metadata])
  await repo.insert({ id: 1, theDate: new Date(1976, 6, 16, 8, 7, 6) })
  console.log(await repo.findFirst())
})

```

**Comment by noam-honig** [comment]
I've created a code sandbox where you can test this with mariadb - maybe you can adjust it to reproduce your issue?

https://codesandbox.io/p/sandbox/holy-pine-g42rqz?file=%2Fsrc%2Findex.ts%3A21%2C10
