### ISSUE TITLE
Missing import to remultNextApp in docs

### ISSUE THREAD

**Issue by OshriAsulin** [remult/remult#250]
**Describe the bug**
I try to implement integration to Ably by the guide in docs, but is missing some import there

**To Reproduce**
1. Go to - https://remult.dev/tutorials/react-next/deployment.html#livequery-serverless-support
2. Scroll down to - step 6 
3. Import to `remultNextApp` is missing 

**Expected behavior**

**Screenshots**

<img width="509" alt="צילום מסך 2023-09-29 104315" src="https://github.com/remult/remult/assets/114335827/74c5534b-36f5-419a-8de2-ef0e06188cfe">

**Desktop (please complete the following information):**
 - Browser  chrome

@noam-honig  Let me know if you want I open a PR for this issue

**Comment by noam-honig** [comment]
The page you are referring two is part of a tutorial on how to use remult with next - the `remultNextApp` is configured earlier in the setup stage:
https://remult.dev/tutorials/react-next/


If you're using express  - set the `subscriptionServer` for you existing `remultExpress` in `api.ts`

**Comment by OshriAsulin** [comment]
You right I am confused, I using express and react so I will try your suggestions
