### ISSUE TITLE
BackendMethod that calls save() doesn't update id on the client side

### ISSUE THREAD

**Issue by groszdaniel** [remult/remult#255]
**Describe the bug**

When an entity is created with `create()` and then saved with `save()`, the `save()` method normally creates a new `id` when inserting the row into the database. When `save()` is called directly from the client, it properly updates the `id` on the client side too. However, if instead the client calls an entity backend method, which calls `save()`, the `id` is not updated on the client.

Such backend methods would be useful when some additional server-side processing is needed when creating an entity, and these should ideally be done as a single server-side transaction.

**To Reproduce**

On the server, create a backend method like this:

```javascript
@Entity("foo", {
  allowApiCrud: true
})
export class Foo extends IdEntity {
  //...
  @BackendMethod({ allowed: true }) async saveAndDoSomething(remult?: Remult) {
    this.save()
    // Some additional operations
  }
}
```

On the client side, call it like this:
```javascript
const foo = remult.repo(Foo).create()
await foo.saveAndDoSomething()
```

After this, `foo.id` remains unchanged. Calling `await remult.repo(Foo).findId(foo.id)` returns undefined.

**Expected behavior**

`foo.id` is updated on the client side to the `id` with which it's saved to the database.

**Workarounds**

- Saving the entity with `save()`, then doing additional operations with a separate backend method. The downside is that sometimes saving the entity and the additional operations should run in a transaction, the client shouldn't be allowed to save the entity without doing the additional operations.
- Creating a static backend factory method that creates the entity with `insert()`, does additional operations, then returns it. The downside is that, in my experience, when entities are returned from backend methods, the client receives them as plain JavaScript objects, rather than as proper entity instances.
- Returning the new `id` from the backend method, and then manually updating the `id` of the entity on the client side based on it. Works, but is obviously a workaround.

**Comment by noam-honig** [comment]
Hi @groszdaniel 

Can you try adding await to the save? I think it'll help
```diff
@Entity("foo", {
  allowApiCrud: true
})
export class Foo extends IdEntity {
  //...
  @BackendMethod({ allowed: true }) async saveAndDoSomething(remult?: Remult) {
+    await this.save()
    // Some additional operations
  }
}
```

**Comment by groszdaniel** [comment]
Ah, stupid mistake that I left it out in this example code, but no, it doesn't fix it.

**Comment by noam-honig** [comment]
Hi @groszdaniel ,

I tried to reproduce your issue on this repo and I get the id ok - can you take a look?
https://github.com/noam-honig/remult_issue_255

**Comment by groszdaniel** [comment]
I can reproduce it with your sample code too.

Add this at the bottom of Task.ts:
```typescript
Object.assign(globalThis, { remult, Task })
``` 
along with adding `remult` to the imports.

Then, in the browser console, write 
```typescript
var task = remult.repo(Task).create()
await task.saveAndDo()
``` 
After this, `task.id` remains an empty string.

**Comment by noam-honig** [comment]
@groszdaniel what is your motivation in doing `Object.assign(globalThis,{remult,Task})` - or where do you use it?

**Comment by noam-honig** [comment]
Hi @groszdaniel cool find - actually my repro was wrong and i used save instead of what you mentioned.

Anyhow - I've fixed it and released a new version - please checkout:
https://github.com/remult/remult/releases/tag/v0.22.9

I also fixed the repo I've created. You can see it working there.

ps
Thanks for the globalThis trick - I didn't think of that :)

**Comment by groszdaniel** [comment]
Thank you, it works now.
