### ISSUE TITLE
Setting column values on insert

### ISSUE THREAD

**Issue by mihaa1** [remult/remult#275]
#question
Say I have this model:
```
export class User {
  @Fields.string()
  id = '';

  @Fields.string({
    validate: Validators.required,
  })
  email = '';
}
```
I would like for the id to get the email value always on insert by default.
Is there a simple way to do this?

**Comment by noam-honig** [comment]
sure:
```ts
@Fields.string<User>({
saving:user=>{
   if (user.id=='')
      user.id = user.email
}
})
id=''
```

**Comment by mihaa1** [comment]
> sure:
> 
> ```ts
> @Fields.string<User>({
> saving:user=>{
>    if (user.id=='')
>       user.id = user.email
> }
> })
> id=''
> ```

Worked! thanks!
