### ISSUE TITLE
Setting field type as type/interface

### ISSUE THREAD

**Issue by mihaa1** [remult/remult#276]
Is it possible to set a field type in an entity to be a custom type or interface I created?

**Comment by noam-honig** [comment]
Hi @mihaa1 

Sure, you can user Field.Json or Field.Object if your db doesn't support json well

**Comment by mihaa1** [comment]
> Hi @mihaa1
> 
> Sure, you can user Field.Json or Field.Object if your db doesn't support json well https://remult.dev/docs/field-types.html#json-field

This is what I'm doing:
```
interface Settings {
  shiftLengthHrs: ShiftLength;
}

@Fields.json()
  settings: Settings = {
    shiftLengthHrs: 1,
  };
```

Is this the recommended way?

**Comment by noam-honig** [comment]
Sure
