### ISSUE TITLE
How to call a backend method on Entity.saving()?

### ISSUE THREAD

**Issue by impleotv** [remult/remult#279]
Hi there,

I have a code that should be executed when the entity is saved, something like this:
```
@Entity<Platform>('platforms', {
    allowApiCrud: true,
    saving: async Platform => {
           const someRepo = remult.repo(MyRepo);
            ...
       if(isBackend()) {            
          myBackendFunction();
       }
      },
})
```
Everything works as expected, but when I try to use something backend related here, the client part ceases to work. 
I found the isBackend() method, but it didn't help me for some reason...

The error I get is related to the backend code I'd like to execute:
```
Uncaught Error: Module "child_process" has been externalized for browser compatibility. Cannot access "child_process.spawn" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:child_process:3:11)
    at udpRecasterCtrl.ts:1:23
```
    

I also tried to create a Controller (  @BackendMethod({ allowed: true })) and calling it instead of invoking the function directly, but it hasn't resolved the issue. How can I invoke a method on the server just before Remult writes to the database, without having to write the DB adapter?

Thanks a lot,

Alex

**Comment by impleotv** [comment]
I managed to get it working by placing import inside the   if(isBackend()) {  } section.
Alex

**Comment by noam-honig** [comment]
Great - know that in the next version, saving will only happen on the backend (as you've expected in the first place )
