### ISSUE TITLE
Support for a different ID generator

### ISSUE THREAD

**Issue by shyakadavis** [remult/remult#289]
**Is your feature request related to a problem? Please describe.**

Hi.

I am new to Remult, and without sounding like a menace, wanted to point out something about the current random ID generator.

Currently, [cuid](https://github.com/paralleldrive/cuid) is used to automatically generate a short random ID. [example](https://remult.dev/tutorials/sveltekit/entities.html#define-the-model)
But, from their project, they say that the package is deprecated due to security.
And while, 
> "the package has been done and API stable for years, and will likely continue to work fine for many more years",

- [source](https://github.com/paralleldrive/cuid/issues/285#issuecomment-1565420395)

I was curious if this poses no threat/problem/worry to Remult itself.

**Describe the solution you'd like**

While I am not well versed in such matters, but having used [nanoid](https://github.com/ai/nanoid) a few times and found it very "nice", I was curious if there would be a way to use this instead, or at the very least, another ID generator.

Regardless of whether this is doable or not, I wish you success with the project.

P.S. I also saw that I could use `uuid`, but wanted to stick to personal preference. 🙂

**Comment by shyakadavis** [comment]
Hi, @noam-honig 

Thanks for clarification. 🙂 

If you don't mind, could you please help me out with pleasing TS. 😅 

It's complaining that:
```
Cannot find name 'ClassFieldDecorator'. Did you mean 'ClassDecorator'?ts(2552)
```
&
```
Type 'StringConstructor' is not assignable to type 'ClassType<string>'.
  Type 'String' is not assignable to type 'string'.
    'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.ts(2322)
```   
  
Here is my `shared/custom.ts` file:
  ```ts
  import { nanoid } from 'nanoid';
import { Field, type FieldOptions, type Remult } from 'remult';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function NanoIdField<entityType = any>(
	...options: (
		| FieldOptions<entityType, string>
		| ((options: FieldOptions<entityType, string>, remult: Remult) => void)
	)[]
): ClassFieldDecorator<entityType, string | undefined> {
	return Field(
		() => String,
		{
			allowApiUpdate: false,
			defaultValue: () => nanoid(),
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
			saving: (_: any, _1: any, r: { value: string }) => {
				if (!r.value) r.value = nanoid();
			}
		},
		...options
	);
}
  ```
---  
But, now that I look at this, I'm convinced that it's just not worth it, and should stick with what you guys offered us. 😄 
  
Please feel free to close or move to a discussion.

**Comment by noam-honig** [comment]
Sorry about that - I gave you the wrong example - here's a new one:
```ts
import { nanoid } from 'nanoid'
import {  Fields, type FieldOptions } from 'remult'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function NanoIdField<entityType = any>(
  ...options: FieldOptions<entityType, string>[]
) {
  return Fields.string<entityType>(
    {
      allowApiUpdate: false,
      defaultValue: () => nanoid(),
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      saving: (_: any, _1: any, r: { value: string }) => {
        if (!r.value) r.value = nanoid()
      },
    },
    ...options
  )
}
```

**Comment by shyakadavis** [comment]
Hey, @noam-honig (sorry for the ping, again)

But it's throwing a new error on the `saving` property:

```
Type '(_: any, _1: any, r: {    value: string;}) => void' is not assignable to type '(entity: entityType, fieldRef: FieldRef<entityType, string>) => any'.
  Target signature provides too few arguments. Expected 3 or more, but got 2.ts(2322)
```

**Comment by noam-honig** [comment]
I apologize, I'm doing a 100 things at a time and didn't test correctly - now I did :)

Here's my test sandbox that demos that it works:
https://codesandbox.io/p/sandbox/nanoidfielddemo-cf42pd

And the code is even simpler
```ts
import { nanoid } from "nanoid";
import { Fields, type FieldOptions } from "remult";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function NanoIdField<entityType = any>(
  ...options: FieldOptions<entityType, string>[]
) {
  return Fields.string<entityType>(
    {
      allowApiUpdate: false,
      defaultValue: () => nanoid(),
      saving: (_, _1, r) => {
        if (!r.value) r.value = nanoid();
      },
    },
    ...options,
  );
}

```

**Comment by shyakadavis** [comment]
> I'm doing a 100 things at a time

Now I feel bad, because I wanted to report that this error persists:

```
Type '(_: any, _1: any, r: any) => void' is not assignable to type '(entity: entityType, fieldRef: FieldRef<entityType, string>) => any'.
  Target signature provides too few arguments. Expected 3 or more, but got 2.ts(2322)
```

I honestly don't know what I'm doing wrong here, but I'm literally copy-pasting that codesandbox snippet. 🥶 

But please take your time. No pressure from me. 🙂

**Comment by noam-honig** [comment]
Check out the sandbox I sent you- I think it works well there

**Comment by noam-honig** [comment]
https://codesandbox.io/p/sandbox/nanoidfielddemo-cf42pd

**Comment by noam-honig** [comment]
> > I'm doing a 100 things at a time
> 
> 
> 
> Now I feel bad, because I wanted to report that this error persists:
> 
> 
> 
> ```
> 
> Type '(_: any, _1: any, r: any) => void' is not assignable to type '(entity: entityType, fieldRef: FieldRef<entityType, string>) => any'.
> 
>   Target signature provides too few arguments. Expected 3 or more, but got 2.ts(2322)
> 
> ```
> 
> 
> 
> I honestly don't know what I'm doing wrong here, but I'm literally copy-pasting that codesandbox snippet. 🥶 
> 
> 
> 
> But please take your time. No pressure from me. 🙂 

Don't worry about me, it was my way to apologize for sending you back and forth. 

Let me know about that sandbox

**Comment by shyakadavis** [comment]
Hey.

I honestly don't get what's wrong.

I've prepared a small reproduction here: https://github.com/shyakadavis/remult-sveltekit-repro

Specifically, the file is this one where the error is being fired: https://github.com/shyakadavis/remult-sveltekit-repro/blob/main/src/shared/custom-fields.ts#L10

Please have a look when you can, and please do tell if you can't reproduce the error.

**Comment by noam-honig** [comment]
Super Super sorry - I was working on a remult branch for the  next version - in the current version of remult, saving takes only two fields
``ts
import { nanoid } from 'nanoid';
import { Fields, type FieldOptions } from 'remult';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function NanoIdField<entityType = any>(...options: FieldOptions<entityType, string>[]) {
	return Fields.string<entityType>(
		{
			allowApiUpdate: false,
			defaultValue: () => nanoid(),
			saving: (_, r) => {
				if (!r.value) r.value = nanoid();
			}
		},
		...options
	);
}

```

Can you try this out and let me know, thanks so much

**Comment by shyakadavis** [comment]
This was it. 🎉 

Thank you very much for the help.

I'll be on the lookout for the next version. Good luck with the release.

---

On a related note, I didn't want to open an issue because you had too much on your plate, but if you get the time this week, could please have a look at this question in your [Discord server](https://discord.com/channels/975754286384418847/1175471280590422236)?

Thanks again.
