### ISSUE TITLE
Saving entity with ObjectId in mongodb

### ISSUE THREAD

**Issue by itamardavidyanLFO** [remult/remult#295]
**Describe the bug**

I'm trying to save entity with `ObjectId` but it's saved as simple string

**To Reproduce**
1. Create entity like this:
```
@Entity('users', {
  allowApiCrud: true,
})
export class User extends IdEntity {
  @Fields.string()
  _id!: ObjectId;

  @Fields.string()
  institutionId!: ObjectId;
}
```
2. Send insert request using the next line in the client:
```
await usersRepo.insert({ institutionId })
```

Furter tries:
3. Add the next options to `institutionId` field:
```
{
    valueConverter: {
      toDb: (v) => new ObjectId(v),
      fromDb: (v) => v,
    }
}
 ```
* Don't forget to add `import { ObjectId } from 'mongodb';`
But then I got error in the client:

```
common.ts:874 Uncaught TypeError: (0 , util_1.promisify) is not a function
    at node_modules/mongodb/lib/bulk/common.js (common.ts:874:30)
    at __require2 (chunk-LFBQMW2U.js?v=6f09f456:19:50)
    at node_modules/mongodb/lib/bulk/ordered.js (ordered.ts:7:1)
    at __require2 (chunk-LFBQMW2U.js?v=6f09f456:19:50)
    at node_modules/mongodb/lib/index.js (index.ts:2:1)
    at __require2 (chunk-LFBQMW2U.js?v=6f09f456:19:50)
    at index.ts:227:42
```

**Expected behavior**
I want to be able to save entity with `ObjectId` value

**Desktop:**
 - OS: Windows
 - Browser: Brave
 - Version: 1.60.118
 - Chromium: 119.0.6045.163 (Official Build) (64-bit)

**Comment by noam-honig** [comment]
Hi @itamardavidyanLFO, I've looked into it and got it to work, checkout the following code sendbox, with two mongo db tables using mongo id:
https://codesandbox.io/p/devbox/mong-db-remult-pch8zc?file=%2Fsrc%2Findex.ts%3A53%2C51

**Comment by itamardavidyan** [comment]
Still creating the relation id (`customerId` in your example) as `string` and not as `ObjectId`
How do you distinguishes between `string` and `ObjectId` and the CodeSandbox terminal?

**Comment by noam-honig** [comment]
@itamardavidyan I see the problem you're facing - I'm on it.

If you need an urgent workaround, let me know - otherwise, I'll probably have a fix before next week

**Comment by noam-honig** [comment]
@itamardavidyan, I've release remult@0.22.11 that solves this issue - checkout this codesandbox:
https://codesandbox.io/p/devbox/mong-db-remult-pch8zc?file=%2Fsrc%2Findex.ts%3A45%2C74

**Comment by itamardavidyan** [comment]
Wow 😲 It was fast.
Thanks 🙏🏾 I will check it soon

**Comment by itamardavidyan** [comment]
Should I add
```
valueConverter: {
      fieldTypeInDb: "dbid",
}
```
also to the relation field?
(`customerId` in your example)

**Comment by noam-honig** [comment]
I don't think it's required - it works without it, but if you want it to be
stored in the db as object db also there, than sure
