### ISSUE TITLE
Pulling from repo does not work in child process

### ISSUE THREAD

**Issue by yossef7525** [remult/remult#296]
**Pulling from repo does not work in child process**
I have code that requires high processing. I don't want the main process of the node to get stuck. I want to transfer the function to a child process.
In the child process when I try to retrieve information from the repo using 'find' or 'count' I get the following error.

...\node_modules\remult\src\data-providers\rest-data-provider.js:311
        return (this.fetch || fetch)(url, {
ReferenceError: fetch is not defined

**To Reproduce**
1. Create child process in node project.
2. Try to access the repo from the child process and perform some query
3. See error in console

Here is a screenshot of the error:
<img width="719" alt="image" src="https://github.com/remult/remult/assets/74179006/e0646c20-4ad9-4690-ba74-e79fdcf2fc02">

**Comment by noam-honig** [comment]
Hi @yossef7525, in the new process, you'll need to set the dataProvider that you want to use with remult - by fefault it's http, and that is why you get the error.

Here's how to solve it:
```ts
remult.dataProvider = await createPostgresDataProvider({connectionString:process.env['DATABASE_URL']})
```

```

**Comment by yossef7525** [comment]
Thanks a lot, a huge help, I've been lingering on this for a long time!
Maybe this is also the place to say thank you for a high-quality and excellent library, I use it a lot ❤️
