### ISSUE TITLE
Provide an option to crash the remultExpress server if ensureSchema fails

### ISSUE THREAD

**Issue by sefininio** [remult/remult#297]
**Is your feature request related to a problem? Please describe.**
When deploying to GCP, pods can't be loaded with dependencies on other pods - so the server might load before the DB instance and ensureSchema will fail silently. This scenario is better treated with `exit 1` so the pod will restart itself until success.

**Describe the solution you'd like**
Add an optional option to remultExpress (defaults to false) that if true, will crash the server when ensureScheme fails.

**Comment by noam-honig** [comment]
checkout  remult@0.23.0-exp.29

**Comment by noam-honig** [comment]
@sefininio can you check it out and let me know if it's ok?

**Comment by sefininio** [comment]
Oh, I completely missed the previous comment (on the same freaking day! - amazing)
I'll try to bring up an env where this can be tested. Thanks!

**Comment by sefininio** [comment]
Yes, that works!
I now get `failed ensure schema of players  Error: connect ECONNREFUSED` which is awesome , thanks man!

**Comment by noam-honig** [comment]
Great - closing the issue
