### ISSUE TITLE
Angular 17 & new Vite builder: When Angular app is built, @Entity metadata is lost

### ISSUE THREAD

**Issue by SpeedoPasanen** [remult/remult#303]
Everything works while running `ng serve` but after `ng build` with either dev or prod conf, Remult can't find entity metadata and all Repository methods fail. Any ideas how to fix this?

I am running Remult in Bun as a separate project, so it's not compiled with the Angular compiler.

Error:

```
main.ts:5 ERROR Error: Menu2 is not a known entity, did you forget to set @Entity() or did you forget to add the '@' before the call to Entity?
    at getEntitySettings (getEntityRef.js:14:34)
    at createOldEntity (RepositoryImplementation.js:483:14)
    at new RepositoryImplementation (RepositoryImplementation.js:84:18)
    at Remult2.repo (context.js:53:33)
    at Object.find (remult-proxy.js:91:50)
    at new _AppComponent (app.component.ts:17:23)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:22:3)
    at getNodeInjectable (core.mjs:4261:38)
    at createRootComponent (core.mjs:15294:31)
    at ComponentFactory.create (core.mjs:15161:19)
```

**Comment by SpeedoPasanen** [comment]
@noam-honig thanks for quick reply again. experimentalDecorators wasn't it, was already enabled.

I copied all entities from the Remult app to under the Angular app and imported them from there, and then everything works. 

So seems when entities are imported from outside the Angular project structure, metadata is stripped when built with `@angular-devkit/build-angular:application` but not when served with`@angular-devkit/build-angular:dev-server`. Maybe some Angular optimization going on?

I want to keep backend and frontend apps separated so I will keep tinkering. If you have any quick bright ideas I welcome them =))

Fyi I have a root tsconfig.json where I define some paths, and is extended by all apps in this repo. Angular imports entities from `@api/*` :

```
{
  "compilerOptions": {
    "paths": {
      "@api/*": ["./apps/api/shared/*"],
      "@clientX/*": ["./apps/clientX/src/*"]
    }
  }
}

```

**Comment by SpeedoPasanen** [comment]
This workaround worked: 
Export remult in my API shared directory, to be imported in Angular app, therefore not importing remult twice as it seems is what happened:

```
// apps/api/shared/remult.ts
export * from 'remult';
```

Angular:
```
import { remult } from '@api/remult';
```

Nothing that can be on the Remult side of things to avoid doing this comes to my mind, but I'm not that smart so maybe you figure out something better   :D

**Comment by yoni-rapoport** [comment]
I think it makes sense that Remult should only be loaded once.

Have you tried tools like pnpm or npm workspaces to get Remult installed once at the top-level node_modules?
