### ISSUE TITLE
liveQuery doesn't work if entity updated on initApi context.

### ISSUE THREAD

**Issue by alexchern** [remult/remult#306]
Hi, 

Hope someone can help me with this issue...

I'm calling a function initMyApp at the app start, something like this:
```
export const api = remultExpress({
    ...
    initApi: initMyApp,
})
```

In the initMyApp function I'm updating the entity (immediately, or after some time, with  setTimeout).
   ```
     const serverStatus = await serverStatusRepo.findId(0);
     await serverStatusRepo.update(0, { state: ServerState.Error, errorMessage: errorMessage });
```
           
The entity is updated without problem, but the frontend that uses liveQuery is never (automatically) updated.   I have to manually refresh the page.
  useEffect(() => {
    return serverStatusRepo.liveQuery().subscribe(status => setServerStatusArray(status.applyChanges));
  }, []);         
  
What am I doing wrong?

As a workaround, I can create a REST endpoint and call it with axios from the same initMyApp. This way liveQuery works, but it is really "not nice" :-(

Thanks,

Alex

**Comment by SpeedoPasanen** [comment]
LiveQueries are obviously disconnected and need to reconnect if your server restarts. My guess is they reconnect after initApi is done.

Maybe do the update in a setTimeout giving clients enough time to reconnect? Or back to the drawing board.. why do you need to restart the server often?

**Comment by noam-honig** [comment]
I'm on it - I need to reproduce it and investigate, but I'm pretty sure
I'll be able to fix it tomorrow

**Comment by impleotv** [comment]
> LiveQueries are obviously disconnected and need to reconnect if your server restarts. My guess is they reconnect after initApi is done.
> 
> Maybe do the update in a setTimeout giving clients enough time to reconnect? Or back to the drawing board.. why do you need to restart the server often? Could there be a better way?

The server is only started once. Of course, I tried the setTimeout. As a matter of fact, I'm trying to update the state after a minute. It just doesn't work from this context, though the db is updated... I need to do some config things on a server start, so the initApi seems to be the right place...

**Comment by noam-honig** [comment]
I've fixed it in:
https://github.com/remult/remult/releases/tag/v0.23.4

Can you check it out and let me know if it's ok?

**Comment by alexchern** [comment]
Yep, this is fixed now. Works like a charm! 
I can now make my code much cleaner (without having to send web requests to myself).
Thanks a lot!
