### ISSUE TITLE
Live Query when using express routing

### ISSUE THREAD

**Issue by yossef7525** [remult/remult#307]
When I update data using express routing as described [here](https://remult.dev/docs/using-remult-in-custom-backend-code.html#using-remult-in-express-routes), I do not receive these changes with a live query

this is my route in express:
```js
app.get('/Building', remultApi.withRemult, async (req, res) => {
    try {
        const repo = remult.repo(Deliveries)
        await repo.update(req.query.packIdReq , {status: "OK"})
        res.send({message: "success"})
    } catch {
        res.send({message: "error"})
    }
})
```
- remult version: 0.23.4

What did I miss?

**Comment by noam-honig** [comment]
Hi @yossef7525,
I've tested and it works - here's a code sandbox that demo's that:

https://codesandbox.io/p/devbox/live-rghmq7

**Comment by yossef7525** [comment]
Works for me, my mistake was redeclaring "remultExpress" in both api.ts file, and index.ts file
