### ISSUE TITLE
Backend method parameter typing issues

### ISSUE THREAD

**Issue by groszdaniel** [remult/remult#327]
### Summary of the problems

- Even though Remult supports a way to detect the types of the parameters of a backend method from decorator metadata, and pass only the id of entities passed as parameters, this doesn't work with the vite sample project.
- With some setups, type detection works on the server but not the client, leading to confusing bugs.
- The parameter types cannot be specified with paramTypes if there are circular dependencies between entities.

### Summary of suggestions

- Document the ways the parameter types of a backend methods can be specified, and their effects.
- Document how to enable decorator metadata in vite projects.
- Allow paramTypes to be a function, to make it possible to specify a class declared later.
- Perhaps: if the client sends a plain object, and the server expects an id, reconstruct the entity based on the id field of the object sent by the client. Or just make sending entities work without having to know the parameter types in advance at all.

### Details
**Context**
When a backend method takes an entity as a parameter, it may be sent in one of two different ways over the REST API:

- As a plain JavaScript object, with all fields of the entity. The backend method sees as a plain object.
- As just the id, from which Remult reconstructs the entity on the server side. The backend method sees a full-fledged entity class instance.

These lead to different behaviors: if a field is modified on the client side before calling the backend method, the server sees the modified field if it is sent as a plain object, while it sees the current value in the database if it's recognized as an entity, and just the id is sent. This even has security implications, as if some security check inside the backend method depends on a field of the entity, the client can cheat if it's sent as a plain object.

It seems like there are two ways to make Remult know that the type is an entity, in which case the second method is used: decorator metadata, and the paramTypes option.

**Problems with decorator metadata**

With the react-vite-express-starter setup, entities are sent as plain objects if paramTypes is not specified: detection based on decorator metadata does not work. (Demonstration: https://github.com/groszdaniel/remult-bug/tree/backendMethod_paramTypes. It has an entity called Foo, and App.tsx calls its backend method. Click the button to call a backend method, and observe the network request.)

Looking around, it seems like vite doesn't support emitDecoratorMetadata, at least out of the box. Idk if Remult is primarily intended to be used with decorator metadata, or if you know of a way to make it work with vite.

In a more complex project I work on, it was even worse: it seems to me that type detection from metadata works on the server side, but not on the (vite-based) client side, so (without setting paramTypes) the server expects just an id, but the client sends an object, which the server doesn't understand, and as a result the backend method sees undefined in the place of the argument. (This is what forced me to investigate this stuff in the first place. For some reason, it did not happen with the react-vite-express-starter-based sample project: perhaps, in that case, type detection doesn't work on the server either for some reason, even though emitDecoratorMetadata is enabled?)

Suggestions/possible solutions:

- Document how to make metadata-based detection work on the client side.
- Document that decorator metadata must be enabled and work on either both the client and the server side, or neither, or else paramTypes must be set on all backend methods that take an entity as a parameter.
- If the server expects an entity, and the client sends an object (instead of just an id), use the id field of that object to query the entity from the database and pass it to the backend method. (Don't just pass the object the client sent: when types are set up properly, the backend method can currently rely on that the object it receives is an actual entity, with its fields as it appears in the database, but passing the object the client sent would break this.)
- Don't rely on metadata on the client side. After all, the client-side part of Remult can check whether the argument passed to the backend method is an entity instance, and only send the id in that case (unless it's explicitly specified as a plain Object in paramTypes). Only the server needs to know the expected type, to tell how to interpret the JSON it receives. (Though this could break existing projects that have metadata being disabled on both sides, as the server would now get an id, when it expects an object.)
- Don't rely on metadata on either side. Specify the arguments' types as part of the request. On the client side, if an argument is an entity instance, send the id, and (in another part of the request) the entity type. On the server side, reconstruct the entity based on the type and the id if (and only if) the client says it's an entity instance. The backend method can check whether the argument it receives is an entity instance, if it needs to know that it's a valid entity for security reasons. This would basically allow dynamic typing of the arguments.

**The circular dependency problem**

The current workaround/solution for the above is to specify the paramTypes option. However, if two entities would need to refer to each other like this, it throws a runtime error:

```typescript
export class Foo extends EntityBase {
  @Fields.cuid()
  id = "";

  @BackendMethod({ allowed: true, paramTypes: [Bar] }) async backendMethod(bar: Bar) {
    // ...
  }
}

export class Bar extends EntityBase {
  @Fields.cuid()
  id = "";

  @BackendMethod({ allowed: true, paramTypes: [Foo] }) async backendMethod(foo: Foo) {
    // ...
  }
}
```

At `paramTypes: [Bar]`, it throws  `ReferenceError: can't access lexical declaration 'Bar' before initialization`, because we try to pass the class Bar, to the BackendMethod decorator, but it's not yet defined. Putting them into two different modules that import each other doesn't make it any better: whichever declaration is executed first will raise the error.

This is an inherent issue resulting from TypeScript decorators being executed immediately at the class declaration others have run into as well:
https://github.com/microsoft/TypeScript/issues/4521
https://stackoverflow.com/questions/58476116/beautiful-fix-for-circular-dependecies-problem-in-javascript-typescript
https://stackoverflow.com/questions/39334698/typescript-decorators-and-circular-dependencies
And it might come up even if decorator metadata-based type detection worked and were used instead of paramTypes:
https://github.com/rbuckton/reflect-metadata/issues/12
https://github.com/microsoft/TypeScript/issues/6404

The usually recommended solution is to take a function that returns a class, rather than the class itself, similarly to how relations take their type arguments in Remult (perhaps for this same reason?), and call it only when needed. It would look like this:
 ```typescript
@BackendMethod({ allowed: true, paramTypes: [() => Foo, () => Foo] }) async backendMethod(foo1: Foo, foo2: Foo) {}
```
or better like this:
 ```typescript
@BackendMethod({ allowed: true, paramTypes: () => [Foo, Foo] }) async backendMethod(foo1: Foo, foo2: Foo) {}
```
or perhaps even like this, it it doesn't cause problems to defer evaluating the options:
 ```typescript
@BackendMethod(() => ({ allowed: true, paramTypes: [Foo, Foo] })) async backendMethod(foo1: Foo, foo2: Foo) {}
```

### Describe alternatives you've considered
A workaround is to just send the id as a string/number, and reconstruct the entity manually on the server with a findId request. Or to set the param type to Object so it's definitely sent as a plain object, and verify it with a database request if needed for security reasons.

There may be some uglier workarounds to the circular dependency issue, like using describeClass at some point the entity classes are already declared, but before the backend methods might actually be called, but at that point it's less of a hassle to just take an id as an argument.

**Comment by noam-honig** [comment]
Hi @groszdaniel love the detailed issue reporting and the depth to which you've entered in this discussion - this is a subject that I've been dealing with for a long time and considered many alternatives - haven't yet completed any of it.

If this is a priority for you, I'll be happy to raise it's priority on the roadmap, would you like to be notified on test versions as they come out, and/or be part of the discussion of alternatives?

**Comment by groszdaniel** [comment]
> Hi @groszdaniel love the detailed issue reporting and the depth to which you've entered in this discussion - this is a subject that I've been dealing with for a long time and considered many alternatives - haven't yet completed any of it.
> 
> If this is a priority for you, I'll be happy to raise it's priority on the roadmap, would you like to be notified on test versions as they come out, and/or be part of the discussion of alternatives?

For the decorator metadata/automatic detection issue, we can work around it by specifying paramTypes. And I'm not very familiar with build systems, so I don't think I can offer more suggestions about that. But I'm happy to test new versions.types = options.paramTypes

For the circular dependence issue, replacing `options.paramTypes` with `typeof options.paramTypes === 'function' ? options.paramTypes() : options.paramTypes` in `server-action.ts` should do the job, shouldn't it?

**Comment by noam-honig** [comment]
Hi @groszdaniel, I agree.

I'm debating the current behavior of entity, where when you set it as a type (using paramTypes) it sends an id and fetches it on the backend - as opposed to sending it's data - I am not sure what is the right solution. I was wondering if you had an opinion on this.

Thank you for the willingness to test new versions, I'll reach back out to you as soon as I have something for you

**Comment by groszdaniel** [comment]
> For the circular dependence issue, replacing `options.paramTypes` with `typeof options.paramTypes === 'function' ? options.paramTypes() : options.paramTypes` in two places in `server-action.ts` should do the job, shouldn't it?

Just realized that won't work, because that would still be run when the class is declared. Rather, replace `types` with `typeof types === 'function' ? types() : types` when passing it to `prepareArgsToSend`/`prepareReceivedArgs`.

> I'm debating the current behavior of entity, where when you set it as a type (using paramTypes) it sends an id and fetches it on the backend - as opposed to sending it's data - I am not sure what is the right solution. I was wondering if you had an opinion on this.

I'm not sure. Reconstructing the entity on the server side is certainly fine if it's unchanged; the effective question is whether any changed fields should be passed to the server (as `this` behaves in the case of entity/controller backend method) or not (as currently happens, when passing a properly typed entity as a parameter).

There are a few more inconsistencies, or at least non-obvious behaviors like this in Remult, stemming from the dual nature of entities as objects, and as things that can be identified with a scalar `id`: for instance, when updating an entity-typed field in another entity (i.e. a many-to-one relation), or putting a condition on it in a `where` option, I never know if I'm supposed to pass an id in the field, or a whole entity object (in the format Remult returns it), or perhaps `{id: entityId}` or  `{$id: entityId}`, or they all work. I haven't played around with the new relation system yet, though, maybe it makes these more natural.

**Comment by noam-honig** [comment]
@groszdaniel, will you be okay with a solution to the circular reference issue? Later I'll continue with the overhall?

```
@BackendMethod({ allowed: true, paramTypes: () => [Foo, Foo] }) async backendMethod(foo1: Foo, foo2: Foo) {}

```

**Comment by groszdaniel** [comment]
> @groszdaniel, will you be okay with a solution to the circular reference issue? Later I'll continue with the overhall?
> 
> ```
> @BackendMethod({ allowed: true, paramTypes: () => [Foo, Foo] }) async backendMethod(foo1: Foo, foo2: Foo) {}
> ```

Looks good, thank you. The other issues are less important, since specifying paramTypes solves them.

**Comment by groszdaniel** [comment]
@noam-honig It doesn't solve it because of this:

> > For the circular dependence issue, replacing `options.paramTypes` with `typeof options.paramTypes === 'function' ? options.paramTypes() : options.paramTypes` in two places in `server-action.ts` should do the job, shouldn't it?
> 
> Just realized that won't work, because that would still be run when the class is declared. Rather, replace `types` with `typeof types === 'function' ? types() : types` when passing it to `prepareArgsToSend`/`prepareReceivedArgs`.

It should work if you run it on `types` before passing it to `prepareArgsToSend`/`prepareReceivedArgs`, or inside those functions on the `types` argument, so that it's only run when the backend method is called, not when the decorator function is executed.

**Comment by noam-honig** [comment]
Will fix tomorrow morning

**Comment by noam-honig** [comment]
Done, please check the latest exp version:
remult@0.25.5-exp.6

**Comment by noam-honig** [comment]
Great, thanks for the feedback
