### ISSUE TITLE
Data too long for JSON Field 

### ISSUE THREAD

**Issue by philhawthorn** [remult/remult#330]
**Describe the bug**
JSON fields are created in the underlying (MySQL) database as TEXT data type which causes "ERROR 1406: Data too long for column 'json' at row 1" if the JSON object is too large.

**To Reproduce**
Create an entity with a JSON field type:

```
@Entity("test",{
    allowApiCrud: true
})
export class Test {
    @Fields.autoIncrement()
    id: number

    @Fields.json()
    json: object
}
```

Insert a large JSON object to the entity.

**Expected behavior**
JSON fields are created with JSON data type to allow for larger JSON objects to be stored.

**Comment by noam-honig** [comment]
Hi @philhawthorn 

I've fixed it - can you install our latest experimental version and test it there?

remult@0.25.5-exp.8

Looking forward to your feedback

**Comment by philhawthorn** [comment]
Hi @noam-honig 

Thanks for the speedy response. Partial success, in that it successfully creates the column with data type JSON, but when I try to load the data back with remult I get the following error:

using code:

```
const repo = remult.repo(Test)
const records = await repo.find();
```

```
{
  message: 'Failed to load from db:json\r\n' +
    'SyntaxError: Unexpected token o in JSON at position 1',
  stack: [
    'Error: Failed to load from db:json\r',
    'SyntaxError: Unexpected token o in JSON at position 1',
    '    at file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/remult-knex/index.js:135:27',
    '    at Array.map (<anonymous>)',
    '    at KnexEntityDataProvider.find (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/remult-knex/index.js:126:18)',
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
    '    at RepositoryImplementation.rawFind (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/src/remult3/RepositoryImplementation.js:361:25)',
    '    at RepositoryImplementation.find (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/src/remult3/RepositoryImplementation.js:367:24)',
    '    at saving (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/src/shared/models/Org.ts:1:4705)',
    '    at Object.info.<computed> [as saving] (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/src/remult3/RepositoryImplementation.js:758:25)',
    '    at rowHelperImplementation.save (file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/src/remult3/RepositoryImplementation.js:1195:21)',
    '    at file:///Users/philiphawthorn/Documents/vscode/vite-ts-project/node_modules/remult/esm/src/data-api.js:230:13'
  ],
  url: '/api/test/22',
  method: 'PUT'
}
```

**Comment by philhawthorn** [comment]
Sorry, didn't mean to close

**Comment by noam-honig** [comment]
Hi Phil, yes - that is strange - with the tests on my machine it works - but on my ci it dosn't - I'm on it, will update you asap

**Comment by noam-honig** [comment]
Are you using mysql or mysql2 in knex config?

**Comment by philhawthorn** [comment]
I'm using mysql2

**Comment by noam-honig** [comment]
I think I've found the issue - previously I stated that mysql doesn't support json.

Based on your issue, I tested mysql and saw that it supports JSON but requires JSON parsing to load the data - so I implemented that.

Apparently that's one of the differences between mysql vs mysql2 - mysql2 returns a json object, while mysql returns a json string :)

I adjusted the code accordingly, all tests are running also in the ci and a new version is imminent

**Comment by noam-honig** [comment]
Please test the latest exp version - remult@0.25.5-exp.9

**Comment by noam-honig** [comment]
If you're curious, you can see in these tests the difference between mysql & mysql2 returning json :

https://github.com/remult/remult/blob/master/projects/tests/dbs/mysql.spec.ts#L64-L71

**Comment by philhawthorn** [comment]
@noam-honig seems to work well, thank you for the speedy turnaround as always.

**Comment by noam-honig** [comment]
I've got this - it seems that knex and mysql2 want you to save with JSON.stringify but load without it :)

Their support for json is not stellar, and it changes between databases.

Anyhow - here's: remult@0.25.5-exp.10

let me know?

**Comment by philhawthorn** [comment]
Works perfectly, thanks so much 👏

**Comment by noam-honig** [comment]
Happy to help
