### ISSUE TITLE
"remult" has no exported member named 'ArrayEntityDataProvider'

### ISSUE THREAD

**Issue by yossef7525** [remult/remult#336]
According to the documentation I can filter data like this:

```js
static titleLengthFilter = Filter.createCustom<Task, { minLength: number }>(
  ({ minLength }) => {
    return ArrayEntityDataProvider.rawFilter( (item) => {
      return item.title?.length>minLength
    })
  });
});
```
But in the latest version I can't import the **ArrayEntityDataProvider** class!
Did you change anything? If so, please update the documentation.

remult version: 0.25.4

Here is a screenshot of the error I got:
![image](https://github.com/remult/remult/assets/74179006/71bce961-c6fc-4c00-b506-db56fada8b20)

**Comment by noam-honig** [comment]
Will have something for you probably tomorrow

**Comment by noam-honig** [comment]
Hi @yossef7525, can you test:
remult@0.25.5-exp.21

npm i remult@0.25.5-exp.21

**Comment by yossef7525** [comment]
Sorry for the late reply, but it didn't help me.
![image](https://github.com/remult/remult/assets/74179006/3d5d4136-7455-4981-a195-8a18bd0ab95e)

**Comment by noam-honig** [comment]
Hi @yossef7525, acn you check the latest version

Try:
npm i remult@latest
And if that doesn't work try:
npm i remult@exp

I tested this and it worked for me :) so please give it another try and we'll take it from there.

**Comment by yossef7525** [comment]
Now it works for me, thank you very much.
