### ISSUE TITLE
Better way to type a string property as a union of string subtypes?

### ISSUE THREAD

**Issue by SpeedoPasanen** [remult/remult#348]
Hi, I don't know if I'm missing something and there's already a less boilerplatey way to do this, than my workaround below?

I have `type Status = 'shipped' | 'processing';` and a field:

```
@Fields.string({allowNull:true})
status?: Status | null = null;
```

This gives me a Type error: `Type 'string' is not assignable to type '"shipped" | "processing" | null | undefined'`

My workaround required using the `object` field type with a valueConverter that just prevents it from being converted to JSON:

```Typescript
  @Fields.object({
    allowNull: true,
    valueConverter: { fromDb: (val) => val || null, toDb: (val) => val || null }
  })
  status?: Status | null = null;
```

**Comment by noam-honig** [comment]
Hi @SpeedoPasanen I tried this in code sandbox and it seems to work well - checkout:
https://codesandbox.io/p/devbox/brave-roentgen-lsdrjp?file=%2Fsrc%2Fshared%2Ftask.ts

I do have some more features planned around this, but I didn't run into the problem that you've run into.


Can you create a small reproduction with the issue you had so that I can see it?


```ts
import { Entity, Fields } from "remult";

export type Status = "shipped" | "processing";

@Entity("tasks", { allowApiCrud: true })
export class Task {
  @Fields.cuid()
  id = "";
  @Fields.string({ allowNull: true })
  status?: Status | null = null;
}

```

**Comment by SpeedoPasanen** [comment]
Actually now that I try again, I never got a build error, just VSCode intelli.

I have a big monorepo with apps starting from AngularJS refactored to TS (still in use, OMG), PHP+JS crap etc and there's just one old .eslintrc in the root. Maybe it's something in this:

```
module.exports = {
    parser: "@typescript-eslint/parser",
    parserOptions: {
      project: "apps/api/tsconfig.json",
      sourceType: "module",
    },
    plugins: ["@typescript-eslint/eslint-plugin"],
    extends: [
      "plugin:@typescript-eslint/recommended",
      "plugin:prettier/recommended",
    ],
    root: true,
    env: {
      node: true,
      jest: true,
    },
    ignorePatterns: [".eslintrc.js"],
    rules: {
      "@typescript-eslint/interface-name-prefix": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  };
  
```

```
Unable to resolve signature of property decorator when called as an expression.
  Argument of type 'ClassFieldDecoratorContext<Party, "locked" | "visitedOpen" | "visited" | "makingOrder" | "ordered" | null> & { name: "status"; private: false; static: false; }' is not assignable to parameter of type 'string | ClassFieldDecoratorContextStub<Party, string | undefined>'.
    Type 'ClassFieldDecoratorContext<Party, "locked" | "visitedOpen" | "visited" | "makingOrder" | "ordered" | null> & { name: "status"; private: false; static: false; }' is not assignable to type 'ClassFieldDecoratorContextStub<Party, string | undefined>'.
      The types of 'access.set' are incompatible between these types.
        Type '(object: Party, value: "locked" | "visitedOpen" | "visited" | "makingOrder" | "ordered" | null) => void' is not assignable to type '(object: Party, value: string | undefined) => void'.
          Types of parameters 'value' and 'value' are incompatible.
            Type 'string | undefined' is not assignable to type '"locked" | "visitedOpen" | "visited" | "makingOrder" | "ordered" | null'.
              Type 'undefined' is not assignable to type '"locked" | "visitedOpen" | "visited" | "makingOrder" | "ordered" | null'.
```

![image](https://github.com/remult/remult/assets/21078412/0755f763-3314-4cd5-a277-edd87fed12d5)

![image](https://github.com/remult/remult/assets/21078412/d79420d8-9dd8-4733-b8ea-2b179686f721)

**Comment by noam-honig** [comment]
I think I know what it is - and it's probably a bug, I'm looking into it now.

My guess is that in the tsconfig used by vscode to check this file,  you do not "experimental" decorators - and it tests the decoratos based on ts5 decorators (that are not yet supported by many esbuild tools) and it does an extra type check.

Let me work somethong out and get back to you

**Comment by noam-honig** [comment]
@SpeedoPasanen we've added a built-in field type for it called @Fields.literal
https://remult.dev/docs/field-types.html#literal-fields-union-of-string-values

Checkout the latest version - https://github.com/remult/remult/releases/tag/v0.26.0
