### ISSUE TITLE
Hono and Elysia Backend Remult Support

### ISSUE THREAD

**Issue by bensos000** [remult/remult#354]
I feel too productive with remult and it would be awesome if it supports bun new api frameworks hono and elysia. nodejs api frameworks like fastify is fast but elysia and hono are top speed frameworks right now. they have the same express like syntax but focusing on speed and with bun it's faster and i would like to support bun api frameworks if possible with the remult team.

![image](https://github.com/remult/remult/assets/85840710/1da12c66-a264-44e5-a279-d9d558a01ce6)

**Comment by noam-honig** [comment]
Hi @bensos000,

I've added support to Hono to our exp version, can you check it out and see that it works for you?

npm i remult@exp

The specific version it was introduced is:
remult@0.25.6-exp.6

**Comment by noam-honig** [comment]
Here's an example :)
```ts
import { Hono } from 'hono'
import { remultHono } from 'remult/remult-hono'

const app = new Hono()

const api = remultHono({}) 
app.route('', api) 

export default app
```

**Comment by bensos000** [comment]
i have tested the basic entity crud operations and it works 
![image](https://github.com/remult/remult/assets/85840710/3f4dfd18-4844-4651-9fb2-84133501ab71)
![image](https://github.com/remult/remult/assets/85840710/a718d30e-1428-4dab-83e3-b2252d3f4aaa)
![image](https://github.com/remult/remult/assets/85840710/691a4ceb-de0b-42fa-8357-1ea5d25c1fad)
![image](https://github.com/remult/remult/assets/85840710/8e8d30fc-e78f-4484-9ae5-a65acc3ecaf1)
![image](https://github.com/remult/remult/assets/85840710/25e6e6da-a0b0-4756-bf90-d2ff93afb10f)
here is the source code with node and typescript : https://github.com/bensos000/hono-remult

**Comment by bensos000** [comment]
i have deleted express from this sample demo and used hono instead and it works with liveQuery 👍 here is the link : https://github.com/bensos000/remultmonorepo

**Comment by noam-honig** [comment]
Looks great - I've also added it to our automatic test suite.
