### ISSUE TITLE
403 status livequery custom monorepo todo app

### ISSUE THREAD

**Issue by bensos000** [remult/remult#355]
when i want to have livequery fetch data in authenticated method it return 403.
here is the code in github: https://github.com/bensos000/remultmonorepo
run it and when it authenticate it will return 403 for tasks list. can you correct the code ?

**Comment by noam-honig** [comment]
I'll look into it Sunday morning

**Comment by yoni-rapoport** [comment]
This seems to be a cookie issue with `bun` and `cookie-session`. Did you try NodeJS?

**Comment by noam-honig** [comment]
Hi @bensos000, we've looked deeper into this, and it seems that the issue here is a problem with the node js package called cookie-session that doesn't work correctly - and starts a new session on each request.

So, once you sign in, and set the user in the session, that user is not in the session in the next request. You can replace the cookie session usage with any other cookie session implementation that is popular in ban and it'll probably work

**Comment by bensos000** [comment]
@noam-honig thanks i will try it and confirm it if it works

**Comment by bensos000** [comment]
i confirm it works with hono and hono-sessions middleware https://github.com/bensos000/remultmonorepo

**Comment by bensos000** [comment]
when i try to make some crud operations from the frontend it returns this 
![image](https://github.com/remult/remult/assets/85840710/46e79ebf-badf-4bdf-98a4-0fd227d9ca3a)
but it works when listing all todos in liveQuery

**Comment by noam-honig** [comment]
Can you share the code?

**Comment by bensos000** [comment]
the code is in the same repo i have commited hono remult server with the new changes in the main branch => https://github.com/bensos000/remultmonorepo

**Comment by noam-honig** [comment]
It seems that you have two versions of remult - one exp in the backend and one 25.5 in the shared. - causing to instances of remult to run in memory.

Can you please align both package.json

**Comment by bensos000** [comment]
i have updated the version of remult to exp in shared package and the same problem persist.

**Comment by yoni-rapoport** [comment]
You probably still have duplicate `remult` packages (two `node_modules/remult` folders) installed somewhere in your project tree.

While we'd like to fix remult to handle these situations better, having only one instance of the package in your tree is better.

Try deleting all `remult` folders and re-running `bun install`.

**Comment by bensos000** [comment]
yes you're right 
![image](https://github.com/remult/remult/assets/85840710/ede8c4a8-5aa8-4b81-adf1-d881982c45f4)
i have shared now only one instance of remult throught the backend package and i confirm it works now
![image](https://github.com/remult/remult/assets/85840710/6a5d37c4-bdd8-440e-91a0-8d24a4e55bde)

**Comment by noam-honig** [comment]
Can you check this out in the latest version, I think it's fixed by now

**Comment by bensos000** [comment]
i have made 2 remult instances in the monorepo like this :
![image](https://github.com/remult/remult/assets/85840710/94f906f5-6a28-451a-9898-c6359ede9761)
![image](https://github.com/remult/remult/assets/85840710/c57a0949-2c47-44d9-9162-de5b4e303f5d)
and i confirm it works now:
![image](https://github.com/remult/remult/assets/85840710/875f13da-893d-4edb-acb8-f8bb260d8df1)

**Comment by noam-honig** [comment]
Perfect.

One more thing, if you want to contribute an example project that shows bun, hono and hono-sessions - it would be a great contribution.

Simply add it to:
https://github.com/remult/remult/tree/master/examples

**Comment by bensos000** [comment]
ok i will make a pull request with an example of bun-hono-monorepo-todo

**Comment by bensos000** [comment]
here is the pr : https://github.com/remult/remult/pull/375

**Comment by noam-honig** [comment]
Thanks - I've merged it
