### ISSUE TITLE
Issue with Repository 'find' Method: Syntax Error Results in Unintended Data Query

### ISSUE THREAD

**Issue by manimorris** [remult/remult#357]
**Description**
Using the Repository `find` method without providing the `where` keyword leads to unexpected behavior. Instead of throwing an error or returning no results, it retrieves all records of the specified entity.

**My Code**
   ```javascript
   const orders = await repo(Order).find({ customerId: entity.id });
   await Promise.all(orders.map(async (order) => { await repo(Order).delete(order.id); }));
   ```
* Note that the `where` keyword is missing in the `find` method.
* The result was that all records of the `Order` entity were retrieved

**Expected behavior**
I expected the `find` method to either throw an error or return no results when the `where` keyword is omitted, rather than retrieving all records of the specified entity.

**Additional context**
This issue could potentially lead to unintended data deletion or manipulation (as in my tragic case..). 
In this case I was using Javascript, I assume that using Typescript would point that issue when compiling the project. Anyway, I assume this is not the expected behavior.

**Comment by SpeedoPasanen** [comment]
I wouldn't change this. It's not the responsibility of the framework or orm or library to enforce how you use it. Sometimes you do need to get all records from a small dataset.

**Comment by noam-honig** [comment]
I agree - this is by design and consistent to other orm's

The use case of fetching all the rows exists

**Comment by noam-honig** [comment]
Although you can define such an error in your code:
```ts
Remult.onFind = (m, o) => {
  console.log(m, o)
  if (!o?.where)
    throw Error('no where');

}
```

By using the onFind handler that runs whenever anyone calls find
