### ISSUE TITLE
feature: ability to add Entity properties that related to Open API

### ISSUE THREAD

**Issue by davidmeirlevy** [remult/remult#360]
consider this ability on an entity:

```ts
@Entity('products', {
  openApi:  {
    // added data to open API json regarding the entity
  }
})
export class Product {
  ...
}
```

what do you think?

**Comment by davidmeirlevy** [comment]
Let's say I want to add: summary, description, servers (dev / staging / prod), externalDocs, or to mention additional body or headers to the requests that aren't mentioned inside the entity (like a middleware that checks different kind of authentication methods that running outside of remult).

**Comment by noam-honig** [comment]
You can do that today, by extending remult EntityOptions etc.... see:
https://remult.dev/docs/custom-options.html

And then process the openApi json file before sending it to swagger:
```ts
const openApiDocument = api.openApiDoc({ title: "remult-react-todo" });
// --> process the json here. to add what you want based on the options you extend
app.get("/api/openApi.json", (req, res) => res.json(openApiDocument));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(openApiDocument));
```
