### ISSUE TITLE
Doc: Offline Support

### ISSUE THREAD

**Issue by robie2011** [remult/remult#366]
[Remult Repo function]( https://remult.dev/docs/ref_remult.html#repo ) allows to provide custom dataprovider for offline support. This is great and exactly what I need. But I don't find any documentation resp. Example how this can be done.

Please add a documentation with example.

**Comment by yoni-rapoport** [comment]
https://remult.dev/docs/databases#frontend-databases

This is an old docs page we need to find a good place for in the current docs... may be what you're looking for

**Comment by noam-honig** [comment]
Hi @robie2011, checkout the release notes for version [0.25](https://github.com/remult/remult/releases/tag/v0.25.0) it has two examples of using frontend databases - we'll also add some docs on that next week.

Let me know if that helps

**Comment by robie2011** [comment]
When I was reading *offline support* I have imagined some kind of caching mechanism which allows to work with remote repository and switch to local repository in case there is no network.

I think maybe one can combine two repositories to one and implement such a mechanism. 
However, thanks for clarification.
