### ISSUE TITLE
Whether to support bun:sqlite

### ISSUE THREAD

**Issue by kk7771** [remult/remult#387]

**Comment by noam-honig** [comment]
@kk7771 If knex supports it, we do to.

If not, can you point me to an example project that uses it, it shouldn't be hard to implement

**Comment by noam-honig** [comment]
@kk7771 Don't close it yet - it shouldn't be too much work - when do you need this?

**Comment by noam-honig** [comment]
Ok - If you want to play, checkout this code:
https://github.com/remult/remult/blob/c5609d11a6eadcf5f9fe93f899cfb1d9a60cced2/projects/core/remult-sql-js.ts#L17

You can probably easily adjust it to use bun sql.

If you get to a point when it'll be more urgent for you, just let me know - I'll be happy to help

**Comment by noam-honig** [comment]
Released in https://github.com/remult/remult/releases/tag/v0.26.0
