### ISSUE TITLE
howto access the repo from backend

### ISSUE THREAD

**Issue by sancelot** [remult/remult#388]
From the backend , is it possible to access the database ?

I tried , but it failed :
        const featuresRepo = remult.repo(Features);
        jsonData.lines.forEach((data: any) => {
          featuresRepo.insert({
            L: data.L,
            R: data.R,
            A: data.A,
          });

      throw new Error('remult object was requested outside of a valid context, try running it within initApi or a remult request cycle');

**Comment by noam-honig** [comment]
Checkout this article - it'll help

https://remult.dev/docs/using-remult-in-custom-backend-code.html

In essence, wrap it with;
await api.withRemult(async ()=>...

**Comment by noam-honig** [comment]
@sancelot did this solution work for you?

**Comment by sancelot** [comment]
> @sancelot did this solution work for you?

I finally preferred to use a direct call to api:
axios.post(
      "http://localhost:3002/api/Features",
      data,
      {
        headers: { "Content-Type": "application/json" }, // Set content type header
      }
    );

**Comment by sancelot** [comment]
Hi,
I migrated to using your api, it works. 

```
 await api.withRemultAsync(request, async () => {
      const featuresRepo = remult.repo(Features);
      console.log("ins,", data);
      await featuresRepo.insert(data);
    });
```
