### ISSUE TITLE
server backend  build fails 

### ISSUE THREAD

**Issue by sancelot** [remult/remult#400]
**Describe the bug**
when building the backend , I have got an unexpected error.
I don't really understand since the backend works in development mode.
I suppose it is related to db entities.

I have not used a db, I am at the moment using json db

my entities are as follow :
```
import { Entity, Fields } from "remult";

@Entity("Features", {
  allowApiCrud: true,
})
export class Features {
  @Fields.cuid()
  id = "";

  @Fields.number()
  deltaA = 0;

  @Fields.number()
  Axis_0_2_Speed = 0;


  @Fields.createdAt()
  createdAt = new Date();
}
```

node_modules/remult/src/remult3/RepositoryImplementation.d.ts:193:5 - error TS2416: Property 'entityRef' in type 'FieldRefImplementation<entityType, valueType>' is not assignable to the same property in base type 'FieldRef<entityType, valueType>'.
  Type 'EntityRef<any>' is not assignable to type 'EntityRef<entityType>'.
    Types of property 'fields' are incompatible.
      Type 'FieldsRef<any>' is not assignable to type 'FieldsRef<entityType>'.
        Type 'FieldsRef<any>' is not assignable to type 'FieldsRefBase<entityType>'.
          The types of 'find(...).entityRef.fields' are incompatible between these types.
            Type 'FieldsRef<any>' is not assignable to type 'FieldsRef<entityType>'.
              Type 'FieldsRef<any>' is not assignable to type '{ [Properties in keyof MembersOnly<entityType>]: NonNullable<entityType[Properties]> extends { id?: string | number; } ? IdFieldRef<entityType, entityType[Properties]> : FieldRef<...>; }'.

193     entityRef: EntityRef<any>;
        ~~~~~~~~~
**To Reproduce**
tsc -p tsconfig.server.json

**Expected behavior**
a dist build 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
Node v20.11.0

**Additional context**

**Comment by noam-honig** [comment]
Hi @sancelot , can you share with me the repo where you get this issue? my github handle  is noamhonig

If not, can you create a small repo based on the tutorial where you can see this issue - I would be happy to see it first hand and solve it

**Comment by noam-honig** [comment]
Hi @sancelot, Sorry about that - I reviewed the issue and we've already fixed it in the dev version that we'll be releasing next week hopefully :)

In the meantime, please add the `"skipLibCheck": true,` setting to the server tsconfig

```
// tsconfig.server.json

{
  "compilerOptions": {
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "skipLibCheck": true, // <- add this please 
    "rootDir": "src"
  },
  "include": ["src/server/**/*", "src/shared/**/*"]
}

```

**Comment by sancelot** [comment]
@noam-honig , thanks for your prompt reply. your fix is working :-)

**Comment by noam-honig** [comment]
Perfect - I also released a new version that should solve this issue (And added an automatic integration test to make sure it never happens again :)

You can try version:
0.25.8
