### ISSUE TITLE
How can i custom the logic of  compile the entity and filter to raw sql?

### ISSUE THREAD

**Issue by zongzheng123** [remult/remult#414]
**Is your feature request related to a problem? Please describe.**
I have a case that need to  use union all instead of or in where condition.

**Describe the solution you'd like**
I can custom the whole sql to adapt to the entity includes every interface on entity

**Describe alternatives you've considered**
now i can use the SqlDatabase.getDb() to connect to the db directly, but there is a problem that i can not directly convert the return data to entity

**Additional context**
no

**Comment by zongzheng123** [comment]
> Hi @zongzheng123,
> 
> There are several approaches here: You can create what I like to call an `sqlWhereFragment` where you define a rule that is based on raw sql and use it just like any other where - checkout this article [remult.dev/docs/custom-filter#leveraging-database-capabilities-with-raw-sql-in-custom-filters](https://remult.dev/docs/custom-filter#leveraging-database-capabilities-with-raw-sql-in-custom-filters)
> 
> To use union all as the source of an entity you can use the entity's `sqlExpression` option: [remult.dev/docs/ref_entity#sqlexpression](https://remult.dev/docs/ref_entity#sqlexpression)
> 
> for example:
> 
> ```ts
> @Entity('people',{
> sqlExpression:`select id,name from employees union all select id,name from contractors`,
> })
> export class Person{
> @Fields.string()
> id=''
> @Fields.string()
> name=''
> }
> ```
> 
> You can also control the saving and deleting so that the correct table get's updated

Thanks for reply, I ever try sqlExpression option, but i found it is only  treated  as a virtual table,  all the condition will append to it, but i need to pass the parameters in it,
my example like select id from user where name = 'xxx' or age = xx order by id desc , now i need to convert it to select id from user where name = 'xxx'  union select id from user where age =xx,
if i use sqlExpression, it looks can not pass the params name and age directly to the sql expression

**Comment by noam-honig** [comment]
I would use https://remult.dev/docs/custom-filter#leveraging-database-capabilities-with-raw-sql-in-custom-filters for it

```ts
export class Person{
...
static mySpecialWhere = Filter.createCustom<Person,{ name:string; age: number}>(
async ({ name, age }) => {
  const person= await dbNamesOf(Person)

  return SqlDatabase.rawFilter(({param}) =>
        `${person.name} = ${param(name)} or ${person.age} = ${param(age)}`
})
}
```

And in your code it would be something like:
```ts
repo(Person).find({where:Person.mySpecialWhere ({name:'noam',age:48})})
```

**Comment by zongzheng123** [comment]
But the way of 'or' will cause performance issues in my case, but you   gave me an idea, i think i can do like this
```
export class Person{
...
static mySpecialWhere = Filter.createCustom<Person,{ name:string; age: number}>(
async ({ name, age }) => {
  const person= await dbNamesOf(Person)

  return SqlDatabase.rawFilter(({param}) =>
        id in (
       select ${person.id} from ${person} where ${person.name} =   ${param(name)}
       union 
       select ${person.id} from ${person} where ${person. age} =   ${param(age)}
    )
})
}
```
what do you think about it ?

**Comment by noam-honig** [comment]
I think that the database will do that for itself. I’ll be very surprised
if union will out perform or in this case

**Comment by zongzheng123** [comment]
```
bind message supplies 8 parameters, but prepared statement "" requires 0:
 select "id", "action_hash", "action_type", "block_height", "sender", "recipient", "gas_price", "gas_limit", "nonce", "amount", "gas_consumed", "chain_id", "encoding", "version", "contract_address", "status", "execution_revert_msg", "payload", (timestamp at time zone 'UTC') as timestamp
 from "block_action" Order By "id" {
  arguments: {
    '$1': 'io1ga073vrnnr20up5w8pqlu7rjs208cuaxk000k2',
    '$2': 20,
    '$3': 'io1ga073vrnnr20up5w8pqlu7rjs208cuaxk000k2',
    '$4': 20,
    '$5': 'io1ga073vrnnr20up5w8pqlu7rjs208cuaxk000k2',
    '$6': 20,
    '$7': 20,
    '$8': 0
  },


call at this 
       const blockActions = await getAnalyzerRepo(BlockAction).find({
            where: BlockAction.blockActionByAccountWhere({
                page: 1,
                limit: 20,
                account: address
            })
        });
        return blockActions
```
it looks like the custom where conditions not appended to the query, so weird.

**Comment by noam-honig** [comment]
Make sure to return the sql string you nuild

**Comment by zongzheng123** [comment]
Look at my code, i returned the filter sql

**Comment by noam-honig** [comment]
Sorry, didn’t see it in the email - only on github.

I’ll reply once I’m in front of a computer

**Comment by zongzheng123** [comment]
Very nice of you, thanks.

**Comment by noam-honig** [comment]
I've created a code sandbox with some basic code that represents what I understood from your code - and I get a different result - can you checkit out?

https://codesandbox.io/p/devbox/hungry-heyrovsky-9cjc8q?file=%2Fsrc%2Findex.ts%3A9%2C15

**Comment by noam-honig** [comment]
I'm getting:
```
syntax error at or near "limit":
 select "id", "sender", "recipient", "contact_address"
 from "blockAction" where ("id"  = any(array(
                                  (select id from "blockAction" where "sender" = $1 order by "id" desc limit $2)
                                  union all
                                  (select id from "blockAction" where "recipient" = $3 order by "id" desc limit $4)
                                  union all
                                  (select id from "blockAction" where undefined = $5 order by "id" desc limit $6)
                                )) limit $7 offset $8
                ) Order By "id" {
  arguments: {
    '$1': 'the address',
    '$2': 20,
    '$3': 'the address',
    '$4': 20,
    '$5': 'the address',
    '$6': 20,
    '$7': 20,
    '$8': 0
  },
  error: error: syntax error at or near "limit"
```

**Comment by noam-honig** [comment]
I've adjusted it a bit to run - and it does run now.

I would compare it's performance with a simple or query that I think may perform just as fast without the hastle:
```ts
await remult.repo(BlockAction).find({
        where: {
            $or:[
              {sender:address},
              {recipient:address},
              {contract_address:address},
            ]
        })
```

**Comment by zongzheng123** [comment]
> I'm getting:
> 
> ```
> syntax error at or near "limit":
>  select "id", "sender", "recipient", "contact_address"
>  from "blockAction" where ("id"  = any(array(
>                                   (select id from "blockAction" where "sender" = $1 order by "id" desc limit $2)
>                                   union all
>                                   (select id from "blockAction" where "recipient" = $3 order by "id" desc limit $4)
>                                   union all
>                                   (select id from "blockAction" where undefined = $5 order by "id" desc limit $6)
>                                 )) limit $7 offset $8
>                 ) Order By "id" {
>   arguments: {
>     '$1': 'the address',
>     '$2': 20,
>     '$3': 'the address',
>     '$4': 20,
>     '$5': 'the address',
>     '$6': 20,
>     '$7': 20,
>     '$8': 0
>   },
>   error: error: syntax error at or near "limit"
> ```

I use the version 0.25  before, after i update the verison to 0.26 then i got the same error as you , i will look into it first, thanks

**Comment by zongzheng123** [comment]
I fixed it, thank you very much, so nice of you

**Comment by noam-honig** [comment]
It just hit me, you may be using an older version of remult. 

In older versions the rawFilter method had a parameter where you set the sql. 
rawFilter(w => w.sql = "select....
