### ISSUE TITLE
On a `500` error, don't retry 50 times

### ISSUE THREAD

**Issue by jycouet** [remult/remult#427]
**Describe the bug**
When frontend repo receive a `500` (at save for example), the action is re executed 50 times.

This was to _smoothen_ the development depending on your context _(express / vite / ...)_. Would be good to revisit [the logic](https://github.com/remult/remult/blob/main/projects/core/src/buildRestDataProvider.ts#L54-L59).

**Expected behavior**
In prod, we should not have 50 retries before showing that an error occurred.

**Comment by noam-honig** [comment]
I've reduced the retry count to 4 retries, one every 500ms - that would strike a good balance - and there is an option to configure it to no retry - what do you think?

**Comment by jycouet** [comment]
Yeah 4 retries & 500ms seems better already.

For the "no retry" option, what about setting the number of retries ? (Like this I can set 0, but also 1 or 2 )

**Comment by jycouet** [comment]
`4 retries & 500ms` on [remult@0.26.11](https://github.com/remult/remult/releases/tag/v0.26.11) is working well.

For prod, I'll keep: 
```ts
remult({
  //...
  error: async (e) => {
    if (e.httpStatusCode == 500) {
      e.sendError(501, e.responseBody)
    }
  }
  //...
})
```

Thx 👍
