### ISSUE TITLE
How to operate res in nextjs project

### ISSUE THREAD

**Issue by zongzheng123** [remult/remult#440]
**Is your feature request related to a problem? Please describe.**
I looked into the remultNextApp definition and do not find how to operate the res object, i want to set res header to each request.

**Describe the solution you'd like**
Pass the res object to some event like initRequest

**Describe alternatives you've considered**

**Additional context**

**Comment by noam-honig** [comment]
Hi @zongzheng123, are you using the next app router or the next pages router?

**Comment by zongzheng123** [comment]
App router,

**Comment by zongzheng123** [comment]
I just try to add some cache control header to the api
Now i found a way to resolve that is writting a  wrap  function out of the GET function exported by remultNextApp
```
const { POST, PUT, DELETE, GET: remultGET } = api;
export async function GET(request: Request) {
  const res = await  remultGET(request)
  console.log('res', res, res.body)
  return res
}
```

**Comment by noam-honig** [comment]
Cool. Let me know if it get the job done
