### ISSUE TITLE
TauriJS support

### ISSUE THREAD

**Issue by dolev146** [remult/remult#444]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I see a good project but I don't know if it fits my current project with Tauri JS desktop app]

**Describe the solution you'd like**

I am developing a desktop app with TauriJS/ElectronJS and I want to use remult 

**Describe alternatives you've considered**

I want to use remult

**Additional context**

tell me if that can be done

**Comment by noam-honig** [comment]
Hi  @dolev146, sure - remult works with any platform that supports javascript and if you run into any issues, I'll be happy to support you and help you get through them.

Did you run into any specific challenges trying to use remult with TauriJS?
