### ISSUE TITLE
Does remult is production ready?

### ISSUE THREAD

**Issue by ddublon** [remult/remult#454]
Yo!
Noam, I read on the website that Remult is already in use in production and battle-tested for an app that manages food supply on Heruko for 16$ a month is that correct?

I want to use Remult in production in a medical app in a surgery room, what are your thoughts?

**Comment by jycouet** [comment]
I would not recommend Javascript in general for something that control a knife in a heart opération 🤣.
Other than that, it's ready 🚀🚀🚀

I have myself multiple apps in production using remult, and it's working like a charm. Even better, when I have a new usecase, either it already exist and I didn't know about either it's a matter of hours to have it !!! 🎉

Probably @noam-honig can add more things 👍

**Comment by ddublon** [comment]
ok, then it only deals with input-output from the system, not something extreme, it can solve for us big communication between teams, and a ton of time.

**Comment by jycouet** [comment]
Sounds like a great usecase 👍

Have fun building, if you need anything, no not hesitate... Here on on discord.

**Comment by noam-honig** [comment]
Hi @ddublon I agree with @jycouet  - we're here to help if you need us
