### ISSUE TITLE
SvelteKit tutorial not consistent

### ISSUE THREAD

**Issue by galaczi** [remult/remult#457]
I am following the Sveltekit tutorial and having some issues understanding why we are doing things.

First we set up the api route in ``src/routes/api/[...remult]/+server.ts``
https://remult.dev/tutorials/sveltekit/

Then we set up the database in ``src/hooks/handleRemult.ts``
https://remult.dev/tutorials/sveltekit/database

I am assuming ``handleRemult`` should be added to ``hooks.server.ts``. Do we even need the api route if we intercept all requests in the hook?

Edit: because in the previous step handleRemult looks completely different:
https://remult.dev/tutorials/sveltekit/auth
```
/**
 * Handle remult server side
 */
const handleRemult: Handle = async ({ event, resolve }) => {
  return await _api.withRemult(event, async () => await resolve(event))
}
```

**Comment by jycouet** [comment]
I'll have a look and update the doc later today. 
Thank you for pointing is out.
