### ISSUE TITLE
Cannot use existing pg pool with SvelteKit

### ISSUE THREAD

**Issue by galaczi** [remult/remult#460]
**Describe the bug**

I am using Remult with Sveltekit and would like to use an existing pg pool. When I do so, I am getting an error.

**To Reproduce**

db.ts

```
import pg from 'pg';
import { DATABASE_URL } from '$env/static/private';

export const pool = new pg.Pool({
  connectionString: DATABASE_URL
})
```

/hooks/handleRemult

```
import type { Handle } from '@sveltejs/kit'
import { _api } from '../routes/api/[...remult]/+server'

export const handleRemult: Handle = async ({ event, resolve }) => {
  return await _api.withRemult(event, async () => await resolve(event))
}
```

hooks.server.ts

```
import { sequence } from "@sveltejs/kit/hooks";
import { handleRemult } from "./hooks/handleRemult";
import { handleAuth } from "./hooks/auth";

export const handle = sequence(handleAuth, handleRemult);
```

src/routes/api/[...remult]/+server.ts
```
import { remultSveltekit } from 'remult/remult-sveltekit'
import { User } from '$lib/shared/User'
import { DATABASE_URL } from '$env/static/private'
import { createPostgresDataProvider } from 'remult/postgres'
import { SqlDatabase } from 'remult'
import { PostgresDataProvider } from 'remult/postgres'
import { pool } from '$lib/server/db'

export const _api = remultSveltekit({
  entities: [User],
  dataProvider: new SqlDatabase(new PostgresDataProvider(pool))
})

export const { GET, POST, PUT, DELETE } = _api
```
I am getting the following error:

```
[vite] Error when evaluating SSR module /src/hooks.server.ts:
|- TypeError: Cannot read properties of undefined (reading 'orderByNullsFirst')
    at new PostgresDataProvider (file:///project/node_modules/remult/esm/postgres/postgres-data-provider.js:35:21)
    at /project/src/routes/api/[...remult]/+server.ts:12:33
    at async instantiateModule (file:///project/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)
 ```

Simply using the connection string works:

```
  dataProvider: createPostgresDataProvider({
    connectionString: DATABASE_URL,
  })
```

**Expected behavior**
My pg pool should work.

**Desktop:**
 - OS: Ubuntu
 - Node: v20.13.1

**Comment by galaczi** [comment]
My mistake. I messed up the setup.

**Comment by jycouet** [comment]
Great!
I started investigating ^^ haha.

You can join discord if you wanna chat (not now), but I mean could be easier to ask a few things.

**Comment by galaczi** [comment]
Ah sorry, I am just getting familiar with this stack. But it may be a real issue after all. Getting the error again.

**Comment by jycouet** [comment]
Can you try adding the option after `new SqlDatabase(new PostgresDataProvider(pool, {} ))` ?

**Comment by galaczi** [comment]
Yes, the error is gone. Thank you!

Btw, the docs here don't use the option:

https://remult.dev/docs/quickstart#connecting-a-database

**Comment by jycouet** [comment]
We should do a quick fix so that you really don't need to pass an empty object ;)
I can't do it today, but in the coming days... Or maybe @noam-honig when he will see this ;)

**Comment by noam-honig** [comment]
Done:

https://github.com/remult/remult/releases/tag/v0.26.15
