### ISSUE TITLE
Live query doesn't get notification about some server-side changes outside backend method

### ISSUE THREAD

**Issue by groszdaniel** [remult/remult#466]
**Describe the bug**
If a backend method starts some process that asynchronously updates an entity in the database after the backend method returns, and a live query watches the entity in question, the live query doesn't get a notification about the change.

The entity does get changed in the database, the live query just doesn't transmit it.

My use case where this problem comes up: The user on the frontend starts some long-running process that runs on the server, whose status and (partial and eventually complete) results are stored on the server in an entity. The frontend should continuously show the current status and results. In a backend method I'd create the entity with an initial "pending" status start the process, and return from the backend method; later the process would update some fields of the entity. On the frontend I'd use a liveQuery to display the current state of the entities in the database matching some criteria (which would typically include the one corresponding to the currently running process). However, because of this bug, the frontend is stuck showing the initial pending state and doesn't show any further changes until a reload.

**To Reproduce**
I made a demo: https://github.com/groszdaniel/remult-bug/tree/liveQuery

The most relevant part is this:
```typescript
@Entity('foo', {
  allowApiCrud: true,
})
export class Foo extends IdEntity {
  @Fields.integer()
  a = 0;
}

@Controller('FooController')
export class FooController {
  @BackendMethod({ allowed: true })
  static async backendMethod() {
    const foo = await remult.repo(Foo).insert({ a: 1 });
    setTimeout(async () => {
      await remult!.repo(Foo).update(foo.id, { a: 2 });
    }, 1000);
  }
}
```

We create an entity, and after a second we update a field.

**Expected behavior**
In the demo, when you click the button, at first a new row should appear with the number 1. After about a second, it should change to 2.

Instead, a new row appears with the number 1, and doesn't change. If you reload, it changes to 2.

**Additional context**
Another alternative would be to only return from the backend method when the process completes, like this:
```typescript
  @BackendMethod({ allowed: true })
  static async backendMethod() {
    const foo = await remult.repo(Foo).insert({ a: 1 });
    await new Promise<void>((resolve) => setTimeout(async () => {
      await remult!.repo(Foo).update(foo.id, { a: 2 });
      resolve();
    }, 1000));
  }
```
But in this case, in the demo project, the frontend only gets updated with the final state after the backend method returns, I guess the JSON storage emulates transactions somehow. Because backend methods run in transactions, waiting for a long process with continuous updates to complete before returning would be undesirable anyway because it could cause deadlocks and because it wouldn't notify the frontend during the process; in the more complex, PostgreSQL+Knex-based project I'm working on, I even got some database errors when trying that ("Error: Transaction query already complete, run with DEBUG=knex:tx for more info").

**Comment by noam-honig** [comment]
Hi @groszdaniel, 
I want to dive deeper into this with you, and help find a solution that you can use - I would like to explain several aspects that are relevant / available for you.

1. backendMethods are (at least currently) runned in a transaction, so that either it all completes or fails - We believe that a backend method represents an atomic operation that should either complete or fail.

2. Calling code from a backend method that'll complete after the backend method is done - is currentl not supported - we can discuss that further and figure out the best way to do that.

3. For long running backend methods, I use the `queued` flag of the backend method. That resolves the original request of the backend method and while the long running backend method continues - the frontend keeps a pooling request to it and follows it's progress - the api for that is not elegant yet - but it works and I use it in production.
Here's an example:
https://stackblitz.com/edit/github-vwfkxu?file=src%2FApp.tsx

4. Matching the transactional nature of backend method - live query messsages from the backend method execution, are fired once the transaction in completed

5. There is another way to update users on things, that's uses the same infrustracture of live query, using SubscriptionChannel - here's an example:
https://stackblitz.com/edit/github-3nmwrp?file=src%2FApp.tsx


We can also do a zoom on this next week if you would like (contact me directly using our discord channel or my twitter channel @noamhonig)

Let me know what you think

**Comment by groszdaniel** [comment]
>     2. Calling code from a backend method that'll complete after the backend method is done - is currentl not supported - we can discuss that further and figure out the best way to do that.

I think the most natural way to handle it would be to treat database operations called after the backend method returns as not being in a single transaction, but just like they were called directly from the frontend, except for not checking authorization. Basically as if there were a begin transaction and a commit transaction at the beginning/end of the backend method; if some instructions are after the commit, so be it. It seems to actually work, in that the database is updated, except for pushing the data down any live query observing it.

You could also provide an option to @BackendMethod to not use a transaction. In that case, any database operations would be treated as if they came directly from the frontend, except for not checking authorization, as would be nested backend method calls (which would themselves use separate transactions if they don't use this hypothetical option). That way things would be consistent between what happens before the backend method returns, and what happens after it. This would also resolve problems when it's desirable for the process to provide continuous updates, but also to only return from the backend method at the end and provide results, in the case when it's used as a REST API call.

I worked around it by manually writing an Express endpoint, using withRemult, in lieu of a backend method. This way it doesn't run in a transaction, and the live query gets updated properly.

We're writing a testing system, we use React and MobX, and we connect a liveQuery into MobX in order to display data such as, in this case, a set of recorded test runs together with their statuses. (Similar expectations would come up when writing a UI to display pipelines in a CI system.) It's natural to use the same code to display the status of the currently running test(s) as to list the earlier ones. This setup does that, and it also displays the progress of a test to another user (or in another window), not just the one who started it. Using a ProgressListener or SubscriptionChannel would need more duplicated code. The variant where it only returns after the test completes (but perhaps still updates the database throughout) would be useful as an API to be called from a CI.

**Comment by groszdaniel** [comment]
> We can also do a zoom on this next week if you would like (contact me directly using our discord channel or my twitter channel @noamhonig)

We can talk some time if you'd like to discuss these things further.

**Comment by noam-honig** [comment]
Hi @groszdaniel - I hear you - I think that the best solutino as you've outlined is to support a variation of backend method that is not a transaction. I'll look into that.


As for mobx - remult has some cool features around it - checkout this pull request to one of our demo projects:
https://github.com/remult/react-vite-express-starter/tree/mobx-with-entity-base

I may find it valuable

**Comment by noam-honig** [comment]
Hi @groszdaniel We've released an options for `transactional:false` in our latest release that I think you'll enjoy
https://github.com/remult/remult/releases/tag/v0.27.7
