### ISSUE TITLE
Cannot insert data when the id of the table is not named id in the database

### ISSUE THREAD

**Issue by tomiy** [remult/remult#474]
**Describe the bug**
Cannot insert data when the id of the table is not named id in the database (at least using mssql)

**To Reproduce**
1. Create any table with an id named something other than id (id_table for instance)
2. perform an insert with repo.insert(obj)
3. An error will be raised stating something about the id column not existing (which it doesn't)

**Expected behavior**
I can insert data into my database

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: latest

**Additional context**
There seems to be hardcoded id keys [here](https://github.com/remult/remult/blob/a887fdc356b3daf8d233ba56b51de47226385617/projects/core/remult-knex/index.ts#L335) and [here](https://github.com/remult/remult/blob/a887fdc356b3daf8d233ba56b51de47226385617/projects/core/remult-knex/index.ts#L336)
Changing both of these lines to respectively dbName instead of key and result[0][this.entity.idMetadata.field.dbName] instead of result[0].id seems to have fixed the problem locally for me, but I couldn't dig deeper to check all cases due to time constraints
This may or may not be local to mssql, tedious & knex

**Comment by noam-honig** [comment]
Can you share a small repo where I can test this? 
Alternatively, can you share the entity? I want to see the Entity decorator id option, and the decorator you've used for the id column

**Comment by noam-honig** [comment]
Did a bit of testing, and I think it only happens with `Fields.autoIncrenent`

I added a test for it and fixed it in the latest version (0.27.4) can you try and let me know if its resloved?

**Comment by tomiy** [comment]
Sweet, thanks for the quick response! I will test it at work tomorrow and get back to you.
Also yes I forgot to specify that my id field is indeed autoIncrement

**Comment by tomiy** [comment]
This still does not seem to work for my case, so I will be a little more specific:
Let's say, for the purposes of harmonizing column names between db tables in my app, I have a mapping file like so:
```ts
@Entity('table', {
  allowApiCrud: Allow.everyone
})
export class TABLE {
  @Fields.autoIncrement({ dbName: 'ID_TABLE' })
  id!: number
}
```
As you can see, my variable is named id but the column name isn't necessarily so.
This still creates errors in the previously stated lines [here](https://github.com/remult/remult/blob/a81dec7ff7ceec9d1eda82f1b35c6da7a81ce2ae/projects/core/remult-knex/index.ts#L335) and [here](https://github.com/remult/remult/blob/a81dec7ff7ceec9d1eda82f1b35c6da7a81ce2ae/projects/core/remult-knex/index.ts#L336)
My personal fix would still be to use dbName instead of key (or a method returning the mapped db name) as key cannot point to the correct column in database in my case.

**Comment by noam-honig** [comment]
Sorry, added two more tests and released a new version:
remult@0.27.5

**Comment by tomiy** [comment]
Sweet! This fixes the problem.

Thanks a lot!
