### ISSUE TITLE
Pb with experimentalDecorators when following react tutorial

### ISSUE THREAD

**Issue by sancelot** [remult/remult#485]
**Describe the bug**
Following the react tutorial and using the step by step option, I have a problem to enable experimentdecorators in tsconfig
 

**To Reproduce**
follow the option2 react step / step tutorial
https://remult.dev/tutorials/react/

I have a project with these tsconfig files:
tsconfig.app.json
tsconfig.json
tsconfig.node.json

setting     "experimentalDecorators": true, in any file results with this message error :
src/remult3/Fields.js:334
        throw new Error("Set the 'experimentalDecorators:true' option in your 'tsconfig' or 'jsconfig' (target undefined)");     
              ^

Error: Set the 'experimentalDecorators:true' option in your 'tsconfig' or 'jsconfig' (target undefined)

**Comment by noam-honig** [comment]
@sancelot p.s. - let me know that it worked

**Comment by noam-honig** [comment]
I've also updated the tutorial at:
https://remult.dev/tutorials/react/

Would love it if you can check and let me know that it's ok

**Comment by sancelot** [comment]
@noam-honig  ,  Endgame : You win

Thanks for your help
