### ISSUE TITLE
Use remult in nest js backend

### ISSUE THREAD

**Issue by guyindepurker** [remult/remult#534]
I need to know how can I use remult in my nestjs backend

**Comment by noam-honig** [comment]
Hi @guyindepurker ,

Checkout the example in:
https://remult.dev/docs/quickstart - select `nest.js` in the tab and you'll see how to connect it.

**Comment by guyindepurker** [comment]
@noam-honig tnx. Its going to work like its works in express with the backend method and all the setup logic

**Comment by noam-honig** [comment]
Yes, let me know if you run into any trouble
