### ISSUE TITLE
Allow.guest or Allow.anonymous

### ISSUE THREAD

**Issue by olragon** [remult/remult#535]
**Is your feature request related to a problem? Please describe.**
Auth.register, Auth.login, and Auth.forgotPassword are guest-only methods.

**Describe the solution you'd like**
Add & validate `Allow.guest`

**Describe alternatives you've considered**
Manually checking with context

**Comment by noam-honig** [comment]
Hi @olragon ,

You're looking for something that'll be the opposite of Allow.authenticated - meaning authenticated users will get a forbidden error?

Something like:
```ts
function notAuthenticated(){
   return !Allow.auhenticated()
}
```

and use it;
```ts
@BackendMethod({allowed:notAuthenticated})
```

I'm wordering about the name - I'm not sure if guest articulates that authenticated users will get an error, maybe guestOnly or notAuthenticated

What do you think?

**Comment by olragon** [comment]
It's good and work for me. Thank you.
