### ISSUE TITLE
ErrorInfo interface refers also the methods and not only field.

### ISSUE THREAD

**Issue by noam-honig** [remult/remult#71]
**Describe the bug**
The `ErrorInfo`'s `modelState` property includes references to the objects fields, but also to the object's methods.

**To Reproduce**
Consider the following class:
```ts
class person{
  firstName='';
  lastName='';
  getFullName(){
  return this.firstName+' '+this.lastName
  }
}
```

**Expected behavior**
When I use the `ErrorInfo` type with it, it should only include firstName and lastName - and not - `getFullName`

**Screenshots**
![image](https://user-images.githubusercontent.com/16635859/171194781-042d6d0a-b699-4eab-a5d5-09c5caa22ae3.png)
The `getFullName` shouldn't appear in the intelisense

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jycouet** [comment]
Isn't it solved with `EntityError` ? _(btw, where to add the doc for it?)_

**Comment by noam-honig** [comment]
Yes it is sloved

 - not sure where to doc it.
I also ran into a few problem trying to use EntityError<T> with Instanceof
