### ISSUE TITLE
Json db doesn't respect `dbName` option on field

### ISSUE THREAD

**Issue by noam-honig** [remult/remult#72]
**Describe the bug**
The `dbName` option of a field, works great in postgres and sql - but doesn't work when it comes to json db.
**To Reproduce**
Consider the following class:
```ts
@Entity("tasks", {
    allowApiCrud: true
})
export class Task {
    @Fields.uuid()
    id!: string;

    @Fields.string({dbName:'theTitle')
    title = '';

    @Fields.boolean()
    completed = false;
}
```

When the data is stored in the `tasks.json` file, the second field is stored as `title` and not `theTitle`

```json
[
  {
    "id":"a",
    "title":"Task a"
  }
]
```
**Expected behavior**
it should be called `theTitle` in the json file:
```json
[
  {
    "id":"a",
    "theTitle":"Task a"
  }
]
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Informagier** [comment]
I believe, the underlying Cause is the ArrayEntityDataProvider (https://github.com/remult/remult/blob/374cb3187fb11fb5fd52cd77a2124c7eda382b78/projects/core/src/data-providers/array-entity-data-provider.ts#L72)

It just maps the column keys without checking the dbName

**Comment by Informagier** [comment]
Okay, sadly, I could not fix it

**Comment by noam-honig** [comment]
You're in the right place, you can take inspiration from the implementation of Mongo at:
https://github.com/remult/remult/blob/master/projects/core/remult-mongo.ts#L34
