### ISSUE TITLE
Scenarios that includes viewmodels.

### ISSUE THREAD

**Issue by 3ldar** [remult/remult#81]
First of all, I would like to thank you for this great library. Using multiple ViewModels for the same entity is a common scenario for web applications (Different validation sets for different operations, hiding and exposing some properties depending on the situations, etc.). I wonder how remult handles this kind of scenario.  It would be nice if you can redirect me to a sample or documentation.

**Comment by noam-honig** [comment]
First of all, thanks :)

With regards to ViewModels, there are several available strategies that you can employ.

* To control the hiding and exposing of properties, you can use the [inclideInApi](https://remult.dev/docs/ref_field.html#includeinapi) option of a field, for example:
```ts
class User{
...
@Fields.string({ includeInApi:false })
password='';
}
```
Or an authorization rule:
```ts
class User{
...
@Fields.string({ includeInApi:"Admin" })
password='';
}
```
Or even a condition that is based on the instance itself:
```ts
class User{
...
@Fields.string<User>({ includeInApi:(remult)=>/* some rule */  })
password='';
}
```

* You can use the [serverExpression](https://remult.dev/docs/ref_field.html#serverexpression) field option, to enrich the view model with server data. Here's [an example from the CRM-Demo](https://github.com/remult/crm-demo/blob/2cde67327c5d4c75debb2b809f2ce5162a4899fc/src/Contacts/Contact.entity.ts#L51)

* You can also use the [sqlExpression](https://remult.dev/docs/ref_field.html#sqlexpression) if you're using Postgres to create more sophisticated sql's

* You can use multiple entities that view the same database table and optionally use inheritance to reduce duplicity, for example:

```ts
@Entity("deliveries")
export class Deliveries {
    @Fields.uuid()
    id?: string;
    @Fields.string()
    name = '';
    @Fields.boolean()
    deleted = false;
}

@Entity<ActiveDeliveries>("activeDeliveries", {
    dbName: 'deliveries',
    backendPrefilter: {
        deleted: false
    }
})
export class ActiveDeliveries extends Deliveries {
}
```

* For the more complex scenarios, you can use the [Backend Methods](https://remult.dev/docs/backendMethods.html)

If you have a specific example that you are interested in, please share it here, and we'll be happy to review it together.
